// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/bitfs/arbitration.proto

package bitfspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BitfsArbitrationService_SubmitClaim_FullMethodName      = "/bitfs.v1.BitfsArbitrationService/SubmitClaim"
	BitfsArbitrationService_GetArbitration_FullMethodName   = "/bitfs.v1.BitfsArbitrationService/GetArbitration"
	BitfsArbitrationService_ListArbitrations_FullMethodName = "/bitfs.v1.BitfsArbitrationService/ListArbitrations"
)

// BitfsArbitrationServiceClient is the client API for BitfsArbitrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BitfsArbitrationService 是买方、卖方与仲裁程序之间的正式仲裁 RPC。
type BitfsArbitrationServiceClient interface {
	SubmitClaim(ctx context.Context, in *SubmitArbitrationClaimRequestV1, opts ...grpc.CallOption) (*SubmitArbitrationClaimResponseV1, error)
	GetArbitration(ctx context.Context, in *GetArbitrationRequestV1, opts ...grpc.CallOption) (*GetArbitrationResponseV1, error)
	ListArbitrations(ctx context.Context, in *ListArbitrationsRequestV1, opts ...grpc.CallOption) (*ListArbitrationsResponseV1, error)
}

type bitfsArbitrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBitfsArbitrationServiceClient(cc grpc.ClientConnInterface) BitfsArbitrationServiceClient {
	return &bitfsArbitrationServiceClient{cc}
}

func (c *bitfsArbitrationServiceClient) SubmitClaim(ctx context.Context, in *SubmitArbitrationClaimRequestV1, opts ...grpc.CallOption) (*SubmitArbitrationClaimResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitArbitrationClaimResponseV1)
	err := c.cc.Invoke(ctx, BitfsArbitrationService_SubmitClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitfsArbitrationServiceClient) GetArbitration(ctx context.Context, in *GetArbitrationRequestV1, opts ...grpc.CallOption) (*GetArbitrationResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArbitrationResponseV1)
	err := c.cc.Invoke(ctx, BitfsArbitrationService_GetArbitration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitfsArbitrationServiceClient) ListArbitrations(ctx context.Context, in *ListArbitrationsRequestV1, opts ...grpc.CallOption) (*ListArbitrationsResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArbitrationsResponseV1)
	err := c.cc.Invoke(ctx, BitfsArbitrationService_ListArbitrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitfsArbitrationServiceServer is the server API for BitfsArbitrationService service.
// All implementations must embed UnimplementedBitfsArbitrationServiceServer
// for forward compatibility.
//
// BitfsArbitrationService 是买方、卖方与仲裁程序之间的正式仲裁 RPC。
type BitfsArbitrationServiceServer interface {
	SubmitClaim(context.Context, *SubmitArbitrationClaimRequestV1) (*SubmitArbitrationClaimResponseV1, error)
	GetArbitration(context.Context, *GetArbitrationRequestV1) (*GetArbitrationResponseV1, error)
	ListArbitrations(context.Context, *ListArbitrationsRequestV1) (*ListArbitrationsResponseV1, error)
	mustEmbedUnimplementedBitfsArbitrationServiceServer()
}

// UnimplementedBitfsArbitrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBitfsArbitrationServiceServer struct{}

func (UnimplementedBitfsArbitrationServiceServer) SubmitClaim(context.Context, *SubmitArbitrationClaimRequestV1) (*SubmitArbitrationClaimResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitClaim not implemented")
}
func (UnimplementedBitfsArbitrationServiceServer) GetArbitration(context.Context, *GetArbitrationRequestV1) (*GetArbitrationResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArbitration not implemented")
}
func (UnimplementedBitfsArbitrationServiceServer) ListArbitrations(context.Context, *ListArbitrationsRequestV1) (*ListArbitrationsResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArbitrations not implemented")
}
func (UnimplementedBitfsArbitrationServiceServer) mustEmbedUnimplementedBitfsArbitrationServiceServer() {
}
func (UnimplementedBitfsArbitrationServiceServer) testEmbeddedByValue() {}

// UnsafeBitfsArbitrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BitfsArbitrationServiceServer will
// result in compilation errors.
type UnsafeBitfsArbitrationServiceServer interface {
	mustEmbedUnimplementedBitfsArbitrationServiceServer()
}

func RegisterBitfsArbitrationServiceServer(s grpc.ServiceRegistrar, srv BitfsArbitrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedBitfsArbitrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BitfsArbitrationService_ServiceDesc, srv)
}

func _BitfsArbitrationService_SubmitClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitArbitrationClaimRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitfsArbitrationServiceServer).SubmitClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BitfsArbitrationService_SubmitClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitfsArbitrationServiceServer).SubmitClaim(ctx, req.(*SubmitArbitrationClaimRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _BitfsArbitrationService_GetArbitration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArbitrationRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitfsArbitrationServiceServer).GetArbitration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BitfsArbitrationService_GetArbitration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitfsArbitrationServiceServer).GetArbitration(ctx, req.(*GetArbitrationRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _BitfsArbitrationService_ListArbitrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArbitrationsRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitfsArbitrationServiceServer).ListArbitrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BitfsArbitrationService_ListArbitrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitfsArbitrationServiceServer).ListArbitrations(ctx, req.(*ListArbitrationsRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// BitfsArbitrationService_ServiceDesc is the grpc.ServiceDesc for BitfsArbitrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BitfsArbitrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bitfs.v1.BitfsArbitrationService",
	HandlerType: (*BitfsArbitrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitClaim",
			Handler:    _BitfsArbitrationService_SubmitClaim_Handler,
		},
		{
			MethodName: "GetArbitration",
			Handler:    _BitfsArbitrationService_GetArbitration_Handler,
		},
		{
			MethodName: "ListArbitrations",
			Handler:    _BitfsArbitrationService_ListArbitrations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bitfs/arbitration.proto",
}
