// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/bitfs/arbitration.proto

package bitfspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArbitrationClaimantRoleV1 是提交 BitFS 仲裁申诉的一方。
type ArbitrationClaimantRoleV1 int32

const (
	ArbitrationClaimantRoleV1_ARBITRATION_CLAIMANT_ROLE_UNSPECIFIED ArbitrationClaimantRoleV1 = 0
	ArbitrationClaimantRoleV1_ARBITRATION_CLAIMANT_ROLE_BUYER       ArbitrationClaimantRoleV1 = 1
	ArbitrationClaimantRoleV1_ARBITRATION_CLAIMANT_ROLE_SELLER      ArbitrationClaimantRoleV1 = 2
)

// Enum value maps for ArbitrationClaimantRoleV1.
var (
	ArbitrationClaimantRoleV1_name = map[int32]string{
		0: "ARBITRATION_CLAIMANT_ROLE_UNSPECIFIED",
		1: "ARBITRATION_CLAIMANT_ROLE_BUYER",
		2: "ARBITRATION_CLAIMANT_ROLE_SELLER",
	}
	ArbitrationClaimantRoleV1_value = map[string]int32{
		"ARBITRATION_CLAIMANT_ROLE_UNSPECIFIED": 0,
		"ARBITRATION_CLAIMANT_ROLE_BUYER":       1,
		"ARBITRATION_CLAIMANT_ROLE_SELLER":      2,
	}
)

func (x ArbitrationClaimantRoleV1) Enum() *ArbitrationClaimantRoleV1 {
	p := new(ArbitrationClaimantRoleV1)
	*p = x
	return p
}

func (x ArbitrationClaimantRoleV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArbitrationClaimantRoleV1) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bitfs_arbitration_proto_enumTypes[0].Descriptor()
}

func (ArbitrationClaimantRoleV1) Type() protoreflect.EnumType {
	return &file_proto_bitfs_arbitration_proto_enumTypes[0]
}

func (x ArbitrationClaimantRoleV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArbitrationClaimantRoleV1.Descriptor instead.
func (ArbitrationClaimantRoleV1) EnumDescriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{0}
}

// ArbitrationStateV1 是一次仲裁的可恢复状态机。
type ArbitrationStateV1 int32

const (
	ArbitrationStateV1_ARBITRATION_STATE_UNSPECIFIED ArbitrationStateV1 = 0
	ArbitrationStateV1_ARBITRATION_STATE_PENDING     ArbitrationStateV1 = 1
	ArbitrationStateV1_ARBITRATION_STATE_APPROVED    ArbitrationStateV1 = 2
	ArbitrationStateV1_ARBITRATION_STATE_REJECTED    ArbitrationStateV1 = 3
	ArbitrationStateV1_ARBITRATION_STATE_DELIVERED   ArbitrationStateV1 = 4
	ArbitrationStateV1_ARBITRATION_STATE_CLOSED      ArbitrationStateV1 = 5
)

// Enum value maps for ArbitrationStateV1.
var (
	ArbitrationStateV1_name = map[int32]string{
		0: "ARBITRATION_STATE_UNSPECIFIED",
		1: "ARBITRATION_STATE_PENDING",
		2: "ARBITRATION_STATE_APPROVED",
		3: "ARBITRATION_STATE_REJECTED",
		4: "ARBITRATION_STATE_DELIVERED",
		5: "ARBITRATION_STATE_CLOSED",
	}
	ArbitrationStateV1_value = map[string]int32{
		"ARBITRATION_STATE_UNSPECIFIED": 0,
		"ARBITRATION_STATE_PENDING":     1,
		"ARBITRATION_STATE_APPROVED":    2,
		"ARBITRATION_STATE_REJECTED":    3,
		"ARBITRATION_STATE_DELIVERED":   4,
		"ARBITRATION_STATE_CLOSED":      5,
	}
)

func (x ArbitrationStateV1) Enum() *ArbitrationStateV1 {
	p := new(ArbitrationStateV1)
	*p = x
	return p
}

func (x ArbitrationStateV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArbitrationStateV1) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bitfs_arbitration_proto_enumTypes[1].Descriptor()
}

func (ArbitrationStateV1) Type() protoreflect.EnumType {
	return &file_proto_bitfs_arbitration_proto_enumTypes[1]
}

func (x ArbitrationStateV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArbitrationStateV1.Descriptor instead.
func (ArbitrationStateV1) EnumDescriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{1}
}

// ArbitrationClaimV1 是自动仲裁的最小证据包。
// seller 申诉必须提供 payload；buyer 申诉可以不提供，由仲裁方尝试恢复。
type ArbitrationClaimV1 struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Ticket        *HashGetTicketV1          `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Payload       []byte                    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ClaimantRole  ArbitrationClaimantRoleV1 `protobuf:"varint,3,opt,name=claimant_role,json=claimantRole,proto3,enum=bitfs.v1.ArbitrationClaimantRoleV1" json:"claimant_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbitrationClaimV1) Reset() {
	*x = ArbitrationClaimV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitrationClaimV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrationClaimV1) ProtoMessage() {}

func (x *ArbitrationClaimV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitrationClaimV1.ProtoReflect.Descriptor instead.
func (*ArbitrationClaimV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{0}
}

func (x *ArbitrationClaimV1) GetTicket() *HashGetTicketV1 {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *ArbitrationClaimV1) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ArbitrationClaimV1) GetClaimantRole() ArbitrationClaimantRoleV1 {
	if x != nil {
		return x.ClaimantRole
	}
	return ArbitrationClaimantRoleV1_ARBITRATION_CLAIMANT_ROLE_UNSPECIFIED
}

// ArbitrationDecisionV1 是仲裁方根据票据与二进制证据给出的业务裁定。
// 资金池的签名与 close 交易由 pool2of3.v1 的仲裁协议承载。
type ArbitrationDecisionV1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence         uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TicketId         []byte                 `protobuf:"bytes,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Approved         bool                   `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	FinalPayoutSat   uint64                 `protobuf:"varint,6,opt,name=final_payout_sat,json=finalPayoutSat,proto3" json:"final_payout_sat,omitempty"`
	SellerPubkey     []byte                 `protobuf:"bytes,7,opt,name=seller_pubkey,json=sellerPubkey,proto3" json:"seller_pubkey,omitempty"`
	RecoveredPayload []byte                 `protobuf:"bytes,8,opt,name=recovered_payload,json=recoveredPayload,proto3" json:"recovered_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArbitrationDecisionV1) Reset() {
	*x = ArbitrationDecisionV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitrationDecisionV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrationDecisionV1) ProtoMessage() {}

func (x *ArbitrationDecisionV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitrationDecisionV1.ProtoReflect.Descriptor instead.
func (*ArbitrationDecisionV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{1}
}

func (x *ArbitrationDecisionV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ArbitrationDecisionV1) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ArbitrationDecisionV1) GetTicketId() []byte {
	if x != nil {
		return x.TicketId
	}
	return nil
}

func (x *ArbitrationDecisionV1) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ArbitrationDecisionV1) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *ArbitrationDecisionV1) GetFinalPayoutSat() uint64 {
	if x != nil {
		return x.FinalPayoutSat
	}
	return 0
}

func (x *ArbitrationDecisionV1) GetSellerPubkey() []byte {
	if x != nil {
		return x.SellerPubkey
	}
	return nil
}

func (x *ArbitrationDecisionV1) GetRecoveredPayload() []byte {
	if x != nil {
		return x.RecoveredPayload
	}
	return nil
}

// ArbitrationRecordV1 是仲裁服务保存与查询的真值记录。
type ArbitrationRecordV1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence         uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	State            ArbitrationStateV1     `protobuf:"varint,3,opt,name=state,proto3,enum=bitfs.v1.ArbitrationStateV1" json:"state,omitempty"`
	Claim            *ArbitrationClaimV1    `protobuf:"bytes,4,opt,name=claim,proto3" json:"claim,omitempty"`
	Decision         *ArbitrationDecisionV1 `protobuf:"bytes,5,opt,name=decision,proto3" json:"decision,omitempty"`
	CreatedAtUnix    int64                  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix    int64                  `protobuf:"varint,7,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	RejectReasonCode string                 `protobuf:"bytes,8,opt,name=reject_reason_code,json=rejectReasonCode,proto3" json:"reject_reason_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArbitrationRecordV1) Reset() {
	*x = ArbitrationRecordV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitrationRecordV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrationRecordV1) ProtoMessage() {}

func (x *ArbitrationRecordV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitrationRecordV1.ProtoReflect.Descriptor instead.
func (*ArbitrationRecordV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{2}
}

func (x *ArbitrationRecordV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ArbitrationRecordV1) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ArbitrationRecordV1) GetState() ArbitrationStateV1 {
	if x != nil {
		return x.State
	}
	return ArbitrationStateV1_ARBITRATION_STATE_UNSPECIFIED
}

func (x *ArbitrationRecordV1) GetClaim() *ArbitrationClaimV1 {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *ArbitrationRecordV1) GetDecision() *ArbitrationDecisionV1 {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *ArbitrationRecordV1) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ArbitrationRecordV1) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *ArbitrationRecordV1) GetRejectReasonCode() string {
	if x != nil {
		return x.RejectReasonCode
	}
	return ""
}

type SubmitArbitrationClaimRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claim         *ArbitrationClaimV1    `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitArbitrationClaimRequestV1) Reset() {
	*x = SubmitArbitrationClaimRequestV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitArbitrationClaimRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitArbitrationClaimRequestV1) ProtoMessage() {}

func (x *SubmitArbitrationClaimRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitArbitrationClaimRequestV1.ProtoReflect.Descriptor instead.
func (*SubmitArbitrationClaimRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitArbitrationClaimRequestV1) GetClaim() *ArbitrationClaimV1 {
	if x != nil {
		return x.Claim
	}
	return nil
}

type SubmitArbitrationClaimResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submitted     bool                   `protobuf:"varint,1,opt,name=submitted,proto3" json:"submitted,omitempty"`
	Decision      *ArbitrationDecisionV1 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	Error         *BitfsErrorV1          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitArbitrationClaimResponseV1) Reset() {
	*x = SubmitArbitrationClaimResponseV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitArbitrationClaimResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitArbitrationClaimResponseV1) ProtoMessage() {}

func (x *SubmitArbitrationClaimResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitArbitrationClaimResponseV1.ProtoReflect.Descriptor instead.
func (*SubmitArbitrationClaimResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitArbitrationClaimResponseV1) GetSubmitted() bool {
	if x != nil {
		return x.Submitted
	}
	return false
}

func (x *SubmitArbitrationClaimResponseV1) GetDecision() *ArbitrationDecisionV1 {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *SubmitArbitrationClaimResponseV1) GetError() *BitfsErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetArbitrationRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArbitrationRequestV1) Reset() {
	*x = GetArbitrationRequestV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArbitrationRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArbitrationRequestV1) ProtoMessage() {}

func (x *GetArbitrationRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArbitrationRequestV1.ProtoReflect.Descriptor instead.
func (*GetArbitrationRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{5}
}

func (x *GetArbitrationRequestV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetArbitrationRequestV1) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type GetArbitrationResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ArbitrationRecordV1   `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Error         *BitfsErrorV1          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArbitrationResponseV1) Reset() {
	*x = GetArbitrationResponseV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArbitrationResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArbitrationResponseV1) ProtoMessage() {}

func (x *GetArbitrationResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArbitrationResponseV1.ProtoReflect.Descriptor instead.
func (*GetArbitrationResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{6}
}

func (x *GetArbitrationResponseV1) GetRecord() *ArbitrationRecordV1 {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetArbitrationResponseV1) GetError() *BitfsErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListArbitrationsRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArbitrationsRequestV1) Reset() {
	*x = ListArbitrationsRequestV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArbitrationsRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArbitrationsRequestV1) ProtoMessage() {}

func (x *ListArbitrationsRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArbitrationsRequestV1.ProtoReflect.Descriptor instead.
func (*ListArbitrationsRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{7}
}

func (x *ListArbitrationsRequestV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListArbitrationsResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ArbitrationRecordV1 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Error         *BitfsErrorV1          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArbitrationsResponseV1) Reset() {
	*x = ListArbitrationsResponseV1{}
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArbitrationsResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArbitrationsResponseV1) ProtoMessage() {}

func (x *ListArbitrationsResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_arbitration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArbitrationsResponseV1.ProtoReflect.Descriptor instead.
func (*ListArbitrationsResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_arbitration_proto_rawDescGZIP(), []int{8}
}

func (x *ListArbitrationsResponseV1) GetItems() []*ArbitrationRecordV1 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListArbitrationsResponseV1) GetError() *BitfsErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_bitfs_arbitration_proto protoreflect.FileDescriptor

const file_proto_bitfs_arbitration_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/bitfs/arbitration.proto\x12\bbitfs.v1\x1a\x18proto/bitfs/common.proto\x1a\x1aproto/bitfs/transfer.proto\"\xab\x01\n" +
	"\x12ArbitrationClaimV1\x121\n" +
	"\x06ticket\x18\x01 \x01(\v2\x19.bitfs.v1.HashGetTicketV1R\x06ticket\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12H\n" +
	"\rclaimant_role\x18\x03 \x01(\x0e2#.bitfs.v1.ArbitrationClaimantRoleV1R\fclaimantRole\"\xa8\x02\n" +
	"\x15ArbitrationDecisionV1\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\fR\bticketId\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\bR\bapproved\x12\x1f\n" +
	"\vreason_code\x18\x05 \x01(\tR\n" +
	"reasonCode\x12(\n" +
	"\x10final_payout_sat\x18\x06 \x01(\x04R\x0efinalPayoutSat\x12#\n" +
	"\rseller_pubkey\x18\a \x01(\fR\fsellerPubkey\x12+\n" +
	"\x11recovered_payload\x18\b \x01(\fR\x10recoveredPayload\"\xf3\x02\n" +
	"\x13ArbitrationRecordV1\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.bitfs.v1.ArbitrationStateV1R\x05state\x122\n" +
	"\x05claim\x18\x04 \x01(\v2\x1c.bitfs.v1.ArbitrationClaimV1R\x05claim\x12;\n" +
	"\bdecision\x18\x05 \x01(\v2\x1f.bitfs.v1.ArbitrationDecisionV1R\bdecision\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\a \x01(\x03R\rupdatedAtUnix\x12,\n" +
	"\x12reject_reason_code\x18\b \x01(\tR\x10rejectReasonCode\"U\n" +
	"\x1fSubmitArbitrationClaimRequestV1\x122\n" +
	"\x05claim\x18\x01 \x01(\v2\x1c.bitfs.v1.ArbitrationClaimV1R\x05claim\"\xab\x01\n" +
	" SubmitArbitrationClaimResponseV1\x12\x1c\n" +
	"\tsubmitted\x18\x01 \x01(\bR\tsubmitted\x12;\n" +
	"\bdecision\x18\x02 \x01(\v2\x1f.bitfs.v1.ArbitrationDecisionV1R\bdecision\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x16.bitfs.v1.BitfsErrorV1R\x05error\"T\n" +
	"\x17GetArbitrationRequestV1\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"\x7f\n" +
	"\x18GetArbitrationResponseV1\x125\n" +
	"\x06record\x18\x01 \x01(\v2\x1d.bitfs.v1.ArbitrationRecordV1R\x06record\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.bitfs.v1.BitfsErrorV1R\x05error\":\n" +
	"\x19ListArbitrationsRequestV1\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x7f\n" +
	"\x1aListArbitrationsResponseV1\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.bitfs.v1.ArbitrationRecordV1R\x05items\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.bitfs.v1.BitfsErrorV1R\x05error*\x91\x01\n" +
	"\x19ArbitrationClaimantRoleV1\x12)\n" +
	"%ARBITRATION_CLAIMANT_ROLE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fARBITRATION_CLAIMANT_ROLE_BUYER\x10\x01\x12$\n" +
	" ARBITRATION_CLAIMANT_ROLE_SELLER\x10\x02*\xd5\x01\n" +
	"\x12ArbitrationStateV1\x12!\n" +
	"\x1dARBITRATION_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ARBITRATION_STATE_PENDING\x10\x01\x12\x1e\n" +
	"\x1aARBITRATION_STATE_APPROVED\x10\x02\x12\x1e\n" +
	"\x1aARBITRATION_STATE_REJECTED\x10\x03\x12\x1f\n" +
	"\x1bARBITRATION_STATE_DELIVERED\x10\x04\x12\x1c\n" +
	"\x18ARBITRATION_STATE_CLOSED\x10\x052\xb7\x02\n" +
	"\x17BitfsArbitrationService\x12d\n" +
	"\vSubmitClaim\x12).bitfs.v1.SubmitArbitrationClaimRequestV1\x1a*.bitfs.v1.SubmitArbitrationClaimResponseV1\x12W\n" +
	"\x0eGetArbitration\x12!.bitfs.v1.GetArbitrationRequestV1\x1a\".bitfs.v1.GetArbitrationResponseV1\x12]\n" +
	"\x10ListArbitrations\x12#.bitfs.v1.ListArbitrationsRequestV1\x1a$.bitfs.v1.ListArbitrationsResponseV1B0Z.github.com/bsv8/go-bitfs/proto/bitfspb;bitfspbb\x06proto3"

var (
	file_proto_bitfs_arbitration_proto_rawDescOnce sync.Once
	file_proto_bitfs_arbitration_proto_rawDescData []byte
)

func file_proto_bitfs_arbitration_proto_rawDescGZIP() []byte {
	file_proto_bitfs_arbitration_proto_rawDescOnce.Do(func() {
		file_proto_bitfs_arbitration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bitfs_arbitration_proto_rawDesc), len(file_proto_bitfs_arbitration_proto_rawDesc)))
	})
	return file_proto_bitfs_arbitration_proto_rawDescData
}

var file_proto_bitfs_arbitration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_bitfs_arbitration_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_bitfs_arbitration_proto_goTypes = []any{
	(ArbitrationClaimantRoleV1)(0),           // 0: bitfs.v1.ArbitrationClaimantRoleV1
	(ArbitrationStateV1)(0),                  // 1: bitfs.v1.ArbitrationStateV1
	(*ArbitrationClaimV1)(nil),               // 2: bitfs.v1.ArbitrationClaimV1
	(*ArbitrationDecisionV1)(nil),            // 3: bitfs.v1.ArbitrationDecisionV1
	(*ArbitrationRecordV1)(nil),              // 4: bitfs.v1.ArbitrationRecordV1
	(*SubmitArbitrationClaimRequestV1)(nil),  // 5: bitfs.v1.SubmitArbitrationClaimRequestV1
	(*SubmitArbitrationClaimResponseV1)(nil), // 6: bitfs.v1.SubmitArbitrationClaimResponseV1
	(*GetArbitrationRequestV1)(nil),          // 7: bitfs.v1.GetArbitrationRequestV1
	(*GetArbitrationResponseV1)(nil),         // 8: bitfs.v1.GetArbitrationResponseV1
	(*ListArbitrationsRequestV1)(nil),        // 9: bitfs.v1.ListArbitrationsRequestV1
	(*ListArbitrationsResponseV1)(nil),       // 10: bitfs.v1.ListArbitrationsResponseV1
	(*HashGetTicketV1)(nil),                  // 11: bitfs.v1.HashGetTicketV1
	(*BitfsErrorV1)(nil),                     // 12: bitfs.v1.BitfsErrorV1
}
var file_proto_bitfs_arbitration_proto_depIdxs = []int32{
	11, // 0: bitfs.v1.ArbitrationClaimV1.ticket:type_name -> bitfs.v1.HashGetTicketV1
	0,  // 1: bitfs.v1.ArbitrationClaimV1.claimant_role:type_name -> bitfs.v1.ArbitrationClaimantRoleV1
	1,  // 2: bitfs.v1.ArbitrationRecordV1.state:type_name -> bitfs.v1.ArbitrationStateV1
	2,  // 3: bitfs.v1.ArbitrationRecordV1.claim:type_name -> bitfs.v1.ArbitrationClaimV1
	3,  // 4: bitfs.v1.ArbitrationRecordV1.decision:type_name -> bitfs.v1.ArbitrationDecisionV1
	2,  // 5: bitfs.v1.SubmitArbitrationClaimRequestV1.claim:type_name -> bitfs.v1.ArbitrationClaimV1
	3,  // 6: bitfs.v1.SubmitArbitrationClaimResponseV1.decision:type_name -> bitfs.v1.ArbitrationDecisionV1
	12, // 7: bitfs.v1.SubmitArbitrationClaimResponseV1.error:type_name -> bitfs.v1.BitfsErrorV1
	4,  // 8: bitfs.v1.GetArbitrationResponseV1.record:type_name -> bitfs.v1.ArbitrationRecordV1
	12, // 9: bitfs.v1.GetArbitrationResponseV1.error:type_name -> bitfs.v1.BitfsErrorV1
	4,  // 10: bitfs.v1.ListArbitrationsResponseV1.items:type_name -> bitfs.v1.ArbitrationRecordV1
	12, // 11: bitfs.v1.ListArbitrationsResponseV1.error:type_name -> bitfs.v1.BitfsErrorV1
	5,  // 12: bitfs.v1.BitfsArbitrationService.SubmitClaim:input_type -> bitfs.v1.SubmitArbitrationClaimRequestV1
	7,  // 13: bitfs.v1.BitfsArbitrationService.GetArbitration:input_type -> bitfs.v1.GetArbitrationRequestV1
	9,  // 14: bitfs.v1.BitfsArbitrationService.ListArbitrations:input_type -> bitfs.v1.ListArbitrationsRequestV1
	6,  // 15: bitfs.v1.BitfsArbitrationService.SubmitClaim:output_type -> bitfs.v1.SubmitArbitrationClaimResponseV1
	8,  // 16: bitfs.v1.BitfsArbitrationService.GetArbitration:output_type -> bitfs.v1.GetArbitrationResponseV1
	10, // 17: bitfs.v1.BitfsArbitrationService.ListArbitrations:output_type -> bitfs.v1.ListArbitrationsResponseV1
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_bitfs_arbitration_proto_init() }
func file_proto_bitfs_arbitration_proto_init() {
	if File_proto_bitfs_arbitration_proto != nil {
		return
	}
	file_proto_bitfs_common_proto_init()
	file_proto_bitfs_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bitfs_arbitration_proto_rawDesc), len(file_proto_bitfs_arbitration_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bitfs_arbitration_proto_goTypes,
		DependencyIndexes: file_proto_bitfs_arbitration_proto_depIdxs,
		EnumInfos:         file_proto_bitfs_arbitration_proto_enumTypes,
		MessageInfos:      file_proto_bitfs_arbitration_proto_msgTypes,
	}.Build()
	File_proto_bitfs_arbitration_proto = out.File
	file_proto_bitfs_arbitration_proto_goTypes = nil
	file_proto_bitfs_arbitration_proto_depIdxs = nil
}
