// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/bitfs/discovery.proto

package bitfspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DemandBroadcastV1 是 BitFS 发现阶段的最小对象。
// 发现只围绕 seed_hash，禁止混入 block_hash、文件大小或块序号。
type DemandBroadcastV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeedHash      []byte                 `protobuf:"bytes,1,opt,name=seed_hash,json=seedHash,proto3" json:"seed_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandBroadcastV1) Reset() {
	*x = DemandBroadcastV1{}
	mi := &file_proto_bitfs_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandBroadcastV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandBroadcastV1) ProtoMessage() {}

func (x *DemandBroadcastV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandBroadcastV1.ProtoReflect.Descriptor instead.
func (*DemandBroadcastV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DemandBroadcastV1) GetSeedHash() []byte {
	if x != nil {
		return x.SeedHash
	}
	return nil
}

var File_proto_bitfs_discovery_proto protoreflect.FileDescriptor

const file_proto_bitfs_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/bitfs/discovery.proto\x12\bbitfs.v1\"0\n" +
	"\x11DemandBroadcastV1\x12\x1b\n" +
	"\tseed_hash\x18\x01 \x01(\fR\bseedHashB0Z.github.com/bsv8/go-bitfs/proto/bitfspb;bitfspbb\x06proto3"

var (
	file_proto_bitfs_discovery_proto_rawDescOnce sync.Once
	file_proto_bitfs_discovery_proto_rawDescData []byte
)

func file_proto_bitfs_discovery_proto_rawDescGZIP() []byte {
	file_proto_bitfs_discovery_proto_rawDescOnce.Do(func() {
		file_proto_bitfs_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bitfs_discovery_proto_rawDesc), len(file_proto_bitfs_discovery_proto_rawDesc)))
	})
	return file_proto_bitfs_discovery_proto_rawDescData
}

var file_proto_bitfs_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_bitfs_discovery_proto_goTypes = []any{
	(*DemandBroadcastV1)(nil), // 0: bitfs.v1.DemandBroadcastV1
}
var file_proto_bitfs_discovery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bitfs_discovery_proto_init() }
func file_proto_bitfs_discovery_proto_init() {
	if File_proto_bitfs_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bitfs_discovery_proto_rawDesc), len(file_proto_bitfs_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bitfs_discovery_proto_goTypes,
		DependencyIndexes: file_proto_bitfs_discovery_proto_depIdxs,
		MessageInfos:      file_proto_bitfs_discovery_proto_msgTypes,
	}.Build()
	File_proto_bitfs_discovery_proto = out.File
	file_proto_bitfs_discovery_proto_goTypes = nil
	file_proto_bitfs_discovery_proto_depIdxs = nil
}
