// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/bitfs/transfer.proto

package bitfspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileQuoteV1 是卖方对一个完整 seed_hash 文件的报价，而非单个对象报价。
type FileQuoteV1 struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	SeedHash                []byte                 `protobuf:"bytes,1,opt,name=seed_hash,json=seedHash,proto3" json:"seed_hash,omitempty"`
	SeedPriceSat            uint64                 `protobuf:"varint,2,opt,name=seed_price_sat,json=seedPriceSat,proto3" json:"seed_price_sat,omitempty"`
	BlockPriceSat           uint64                 `protobuf:"varint,3,opt,name=block_price_sat,json=blockPriceSat,proto3" json:"block_price_sat,omitempty"`
	EndblockPriceSat        uint64                 `protobuf:"varint,4,opt,name=endblock_price_sat,json=endblockPriceSat,proto3" json:"endblock_price_sat,omitempty"`
	FileSize                uint64                 `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	RecommendedFilename     string                 `protobuf:"bytes,6,opt,name=recommended_filename,json=recommendedFilename,proto3" json:"recommended_filename,omitempty"`
	QuoteExpiresAtUnix      int64                  `protobuf:"varint,7,opt,name=quote_expires_at_unix,json=quoteExpiresAtUnix,proto3" json:"quote_expires_at_unix,omitempty"`
	BlockCount              uint32                 `protobuf:"varint,8,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	SellerPubkey            []byte                 `protobuf:"bytes,9,opt,name=seller_pubkey,json=sellerPubkey,proto3" json:"seller_pubkey,omitempty"`
	SupportedArbiterPubkeys [][]byte               `protobuf:"bytes,10,rep,name=supported_arbiter_pubkeys,json=supportedArbiterPubkeys,proto3" json:"supported_arbiter_pubkeys,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FileQuoteV1) Reset() {
	*x = FileQuoteV1{}
	mi := &file_proto_bitfs_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileQuoteV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileQuoteV1) ProtoMessage() {}

func (x *FileQuoteV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileQuoteV1.ProtoReflect.Descriptor instead.
func (*FileQuoteV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *FileQuoteV1) GetSeedHash() []byte {
	if x != nil {
		return x.SeedHash
	}
	return nil
}

func (x *FileQuoteV1) GetSeedPriceSat() uint64 {
	if x != nil {
		return x.SeedPriceSat
	}
	return 0
}

func (x *FileQuoteV1) GetBlockPriceSat() uint64 {
	if x != nil {
		return x.BlockPriceSat
	}
	return 0
}

func (x *FileQuoteV1) GetEndblockPriceSat() uint64 {
	if x != nil {
		return x.EndblockPriceSat
	}
	return 0
}

func (x *FileQuoteV1) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileQuoteV1) GetRecommendedFilename() string {
	if x != nil {
		return x.RecommendedFilename
	}
	return ""
}

func (x *FileQuoteV1) GetQuoteExpiresAtUnix() int64 {
	if x != nil {
		return x.QuoteExpiresAtUnix
	}
	return 0
}

func (x *FileQuoteV1) GetBlockCount() uint32 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *FileQuoteV1) GetSellerPubkey() []byte {
	if x != nil {
		return x.SellerPubkey
	}
	return nil
}

func (x *FileQuoteV1) GetSupportedArbiterPubkeys() [][]byte {
	if x != nil {
		return x.SupportedArbiterPubkeys
	}
	return nil
}

// HashGetTicketV1 是买方签发的统一取货票据。
// seed 与 block 不使用 type 字段区分：seed 的 content_index 固定为 -1，
// block 的 content_index 为从零开始的块序号。
type HashGetTicketV1 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	RootSeedHash   []byte                 `protobuf:"bytes,3,opt,name=root_seed_hash,json=rootSeedHash,proto3" json:"root_seed_hash,omitempty"`
	ContentHash    []byte                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	ContentIndex   int64                  `protobuf:"varint,5,opt,name=content_index,json=contentIndex,proto3" json:"content_index,omitempty"`
	ExpectedSize   uint64                 `protobuf:"varint,6,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	PriceSat       uint64                 `protobuf:"varint,7,opt,name=price_sat,json=priceSat,proto3" json:"price_sat,omitempty"`
	BuyerPubkey    []byte                 `protobuf:"bytes,8,opt,name=buyer_pubkey,json=buyerPubkey,proto3" json:"buyer_pubkey,omitempty"`
	SellerPubkey   []byte                 `protobuf:"bytes,9,opt,name=seller_pubkey,json=sellerPubkey,proto3" json:"seller_pubkey,omitempty"`
	ExpiresAtUnix  int64                  `protobuf:"varint,10,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	BuyerSignature []byte                 `protobuf:"bytes,11,opt,name=buyer_signature,json=buyerSignature,proto3" json:"buyer_signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HashGetTicketV1) Reset() {
	*x = HashGetTicketV1{}
	mi := &file_proto_bitfs_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashGetTicketV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashGetTicketV1) ProtoMessage() {}

func (x *HashGetTicketV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashGetTicketV1.ProtoReflect.Descriptor instead.
func (*HashGetTicketV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *HashGetTicketV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HashGetTicketV1) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HashGetTicketV1) GetRootSeedHash() []byte {
	if x != nil {
		return x.RootSeedHash
	}
	return nil
}

func (x *HashGetTicketV1) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *HashGetTicketV1) GetContentIndex() int64 {
	if x != nil {
		return x.ContentIndex
	}
	return 0
}

func (x *HashGetTicketV1) GetExpectedSize() uint64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

func (x *HashGetTicketV1) GetPriceSat() uint64 {
	if x != nil {
		return x.PriceSat
	}
	return 0
}

func (x *HashGetTicketV1) GetBuyerPubkey() []byte {
	if x != nil {
		return x.BuyerPubkey
	}
	return nil
}

func (x *HashGetTicketV1) GetSellerPubkey() []byte {
	if x != nil {
		return x.SellerPubkey
	}
	return nil
}

func (x *HashGetTicketV1) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *HashGetTicketV1) GetBuyerSignature() []byte {
	if x != nil {
		return x.BuyerSignature
	}
	return nil
}

// HashDeliveryV1 是卖方针对一张 HashGetTicketV1 的二进制交付。
type HashDeliveryV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashDeliveryV1) Reset() {
	*x = HashDeliveryV1{}
	mi := &file_proto_bitfs_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashDeliveryV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashDeliveryV1) ProtoMessage() {}

func (x *HashDeliveryV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashDeliveryV1.ProtoReflect.Descriptor instead.
func (*HashDeliveryV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *HashDeliveryV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HashDeliveryV1) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *HashDeliveryV1) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *HashDeliveryV1) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SubmitFileQuoteResponseV1 是 buyer 接收卖方报价的响应。
type SubmitFileQuoteResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         *BitfsErrorV1          `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFileQuoteResponseV1) Reset() {
	*x = SubmitFileQuoteResponseV1{}
	mi := &file_proto_bitfs_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFileQuoteResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFileQuoteResponseV1) ProtoMessage() {}

func (x *SubmitFileQuoteResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bitfs_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFileQuoteResponseV1.ProtoReflect.Descriptor instead.
func (*SubmitFileQuoteResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_bitfs_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitFileQuoteResponseV1) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitFileQuoteResponseV1) GetError() *BitfsErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_bitfs_transfer_proto protoreflect.FileDescriptor

const file_proto_bitfs_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/bitfs/transfer.proto\x12\bbitfs.v1\x1a\x18proto/bitfs/common.proto\"\xab\x03\n" +
	"\vFileQuoteV1\x12\x1b\n" +
	"\tseed_hash\x18\x01 \x01(\fR\bseedHash\x12$\n" +
	"\x0eseed_price_sat\x18\x02 \x01(\x04R\fseedPriceSat\x12&\n" +
	"\x0fblock_price_sat\x18\x03 \x01(\x04R\rblockPriceSat\x12,\n" +
	"\x12endblock_price_sat\x18\x04 \x01(\x04R\x10endblockPriceSat\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x04R\bfileSize\x121\n" +
	"\x14recommended_filename\x18\x06 \x01(\tR\x13recommendedFilename\x121\n" +
	"\x15quote_expires_at_unix\x18\a \x01(\x03R\x12quoteExpiresAtUnix\x12\x1f\n" +
	"\vblock_count\x18\b \x01(\rR\n" +
	"blockCount\x12#\n" +
	"\rseller_pubkey\x18\t \x01(\fR\fsellerPubkey\x12:\n" +
	"\x19supported_arbiter_pubkeys\x18\n" +
	" \x03(\fR\x17supportedArbiterPubkeys\"\x95\x03\n" +
	"\x0fHashGetTicketV1\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12$\n" +
	"\x0eroot_seed_hash\x18\x03 \x01(\fR\frootSeedHash\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\fR\vcontentHash\x12#\n" +
	"\rcontent_index\x18\x05 \x01(\x03R\fcontentIndex\x12#\n" +
	"\rexpected_size\x18\x06 \x01(\x04R\fexpectedSize\x12\x1b\n" +
	"\tprice_sat\x18\a \x01(\x04R\bpriceSat\x12!\n" +
	"\fbuyer_pubkey\x18\b \x01(\fR\vbuyerPubkey\x12#\n" +
	"\rseller_pubkey\x18\t \x01(\fR\fsellerPubkey\x12&\n" +
	"\x0fexpires_at_unix\x18\n" +
	" \x01(\x03R\rexpiresAtUnix\x12'\n" +
	"\x0fbuyer_signature\x18\v \x01(\fR\x0ebuyerSignature\"\x88\x01\n" +
	"\x0eHashDeliveryV1\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\fR\vcontentHash\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"e\n" +
	"\x19SubmitFileQuoteResponseV1\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.bitfs.v1.BitfsErrorV1R\x05error2b\n" +
	"\x11BitfsBuyerService\x12M\n" +
	"\x0fSubmitFileQuote\x12\x15.bitfs.v1.FileQuoteV1\x1a#.bitfs.v1.SubmitFileQuoteResponseV12T\n" +
	"\x12BitfsSellerService\x12>\n" +
	"\aDeliver\x12\x19.bitfs.v1.HashGetTicketV1\x1a\x18.bitfs.v1.HashDeliveryV1B0Z.github.com/bsv8/go-bitfs/proto/bitfspb;bitfspbb\x06proto3"

var (
	file_proto_bitfs_transfer_proto_rawDescOnce sync.Once
	file_proto_bitfs_transfer_proto_rawDescData []byte
)

func file_proto_bitfs_transfer_proto_rawDescGZIP() []byte {
	file_proto_bitfs_transfer_proto_rawDescOnce.Do(func() {
		file_proto_bitfs_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bitfs_transfer_proto_rawDesc), len(file_proto_bitfs_transfer_proto_rawDesc)))
	})
	return file_proto_bitfs_transfer_proto_rawDescData
}

var file_proto_bitfs_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_bitfs_transfer_proto_goTypes = []any{
	(*FileQuoteV1)(nil),               // 0: bitfs.v1.FileQuoteV1
	(*HashGetTicketV1)(nil),           // 1: bitfs.v1.HashGetTicketV1
	(*HashDeliveryV1)(nil),            // 2: bitfs.v1.HashDeliveryV1
	(*SubmitFileQuoteResponseV1)(nil), // 3: bitfs.v1.SubmitFileQuoteResponseV1
	(*BitfsErrorV1)(nil),              // 4: bitfs.v1.BitfsErrorV1
}
var file_proto_bitfs_transfer_proto_depIdxs = []int32{
	4, // 0: bitfs.v1.SubmitFileQuoteResponseV1.error:type_name -> bitfs.v1.BitfsErrorV1
	0, // 1: bitfs.v1.BitfsBuyerService.SubmitFileQuote:input_type -> bitfs.v1.FileQuoteV1
	1, // 2: bitfs.v1.BitfsSellerService.Deliver:input_type -> bitfs.v1.HashGetTicketV1
	3, // 3: bitfs.v1.BitfsBuyerService.SubmitFileQuote:output_type -> bitfs.v1.SubmitFileQuoteResponseV1
	2, // 4: bitfs.v1.BitfsSellerService.Deliver:output_type -> bitfs.v1.HashDeliveryV1
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bitfs_transfer_proto_init() }
func file_proto_bitfs_transfer_proto_init() {
	if File_proto_bitfs_transfer_proto != nil {
		return
	}
	file_proto_bitfs_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bitfs_transfer_proto_rawDesc), len(file_proto_bitfs_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_bitfs_transfer_proto_goTypes,
		DependencyIndexes: file_proto_bitfs_transfer_proto_depIdxs,
		MessageInfos:      file_proto_bitfs_transfer_proto_msgTypes,
	}.Build()
	File_proto_bitfs_transfer_proto = out.File
	file_proto_bitfs_transfer_proto_goTypes = nil
	file_proto_bitfs_transfer_proto_depIdxs = nil
}
