// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/bitfs/transfer.proto

package bitfspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BitfsBuyerService_SubmitFileQuote_FullMethodName = "/bitfs.v1.BitfsBuyerService/SubmitFileQuote"
)

// BitfsBuyerServiceClient is the client API for BitfsBuyerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BitfsBuyerService 是 buyer 在发现之后接收卖方报价的服务端接口。
type BitfsBuyerServiceClient interface {
	SubmitFileQuote(ctx context.Context, in *FileQuoteV1, opts ...grpc.CallOption) (*SubmitFileQuoteResponseV1, error)
}

type bitfsBuyerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBitfsBuyerServiceClient(cc grpc.ClientConnInterface) BitfsBuyerServiceClient {
	return &bitfsBuyerServiceClient{cc}
}

func (c *bitfsBuyerServiceClient) SubmitFileQuote(ctx context.Context, in *FileQuoteV1, opts ...grpc.CallOption) (*SubmitFileQuoteResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFileQuoteResponseV1)
	err := c.cc.Invoke(ctx, BitfsBuyerService_SubmitFileQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitfsBuyerServiceServer is the server API for BitfsBuyerService service.
// All implementations must embed UnimplementedBitfsBuyerServiceServer
// for forward compatibility.
//
// BitfsBuyerService 是 buyer 在发现之后接收卖方报价的服务端接口。
type BitfsBuyerServiceServer interface {
	SubmitFileQuote(context.Context, *FileQuoteV1) (*SubmitFileQuoteResponseV1, error)
	mustEmbedUnimplementedBitfsBuyerServiceServer()
}

// UnimplementedBitfsBuyerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBitfsBuyerServiceServer struct{}

func (UnimplementedBitfsBuyerServiceServer) SubmitFileQuote(context.Context, *FileQuoteV1) (*SubmitFileQuoteResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitFileQuote not implemented")
}
func (UnimplementedBitfsBuyerServiceServer) mustEmbedUnimplementedBitfsBuyerServiceServer() {}
func (UnimplementedBitfsBuyerServiceServer) testEmbeddedByValue()                           {}

// UnsafeBitfsBuyerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BitfsBuyerServiceServer will
// result in compilation errors.
type UnsafeBitfsBuyerServiceServer interface {
	mustEmbedUnimplementedBitfsBuyerServiceServer()
}

func RegisterBitfsBuyerServiceServer(s grpc.ServiceRegistrar, srv BitfsBuyerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBitfsBuyerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BitfsBuyerService_ServiceDesc, srv)
}

func _BitfsBuyerService_SubmitFileQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileQuoteV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitfsBuyerServiceServer).SubmitFileQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BitfsBuyerService_SubmitFileQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitfsBuyerServiceServer).SubmitFileQuote(ctx, req.(*FileQuoteV1))
	}
	return interceptor(ctx, in, info, handler)
}

// BitfsBuyerService_ServiceDesc is the grpc.ServiceDesc for BitfsBuyerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BitfsBuyerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bitfs.v1.BitfsBuyerService",
	HandlerType: (*BitfsBuyerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitFileQuote",
			Handler:    _BitfsBuyerService_SubmitFileQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bitfs/transfer.proto",
}

const (
	BitfsSellerService_Deliver_FullMethodName = "/bitfs.v1.BitfsSellerService/Deliver"
)

// BitfsSellerServiceClient is the client API for BitfsSellerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BitfsSellerService 是 seller 接收票据并返回二进制交付的服务端接口。
type BitfsSellerServiceClient interface {
	Deliver(ctx context.Context, in *HashGetTicketV1, opts ...grpc.CallOption) (*HashDeliveryV1, error)
}

type bitfsSellerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBitfsSellerServiceClient(cc grpc.ClientConnInterface) BitfsSellerServiceClient {
	return &bitfsSellerServiceClient{cc}
}

func (c *bitfsSellerServiceClient) Deliver(ctx context.Context, in *HashGetTicketV1, opts ...grpc.CallOption) (*HashDeliveryV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashDeliveryV1)
	err := c.cc.Invoke(ctx, BitfsSellerService_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitfsSellerServiceServer is the server API for BitfsSellerService service.
// All implementations must embed UnimplementedBitfsSellerServiceServer
// for forward compatibility.
//
// BitfsSellerService 是 seller 接收票据并返回二进制交付的服务端接口。
type BitfsSellerServiceServer interface {
	Deliver(context.Context, *HashGetTicketV1) (*HashDeliveryV1, error)
	mustEmbedUnimplementedBitfsSellerServiceServer()
}

// UnimplementedBitfsSellerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBitfsSellerServiceServer struct{}

func (UnimplementedBitfsSellerServiceServer) Deliver(context.Context, *HashGetTicketV1) (*HashDeliveryV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedBitfsSellerServiceServer) mustEmbedUnimplementedBitfsSellerServiceServer() {}
func (UnimplementedBitfsSellerServiceServer) testEmbeddedByValue()                            {}

// UnsafeBitfsSellerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BitfsSellerServiceServer will
// result in compilation errors.
type UnsafeBitfsSellerServiceServer interface {
	mustEmbedUnimplementedBitfsSellerServiceServer()
}

func RegisterBitfsSellerServiceServer(s grpc.ServiceRegistrar, srv BitfsSellerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBitfsSellerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BitfsSellerService_ServiceDesc, srv)
}

func _BitfsSellerService_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashGetTicketV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitfsSellerServiceServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BitfsSellerService_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitfsSellerServiceServer).Deliver(ctx, req.(*HashGetTicketV1))
	}
	return interceptor(ctx, in, info, handler)
}

// BitfsSellerService_ServiceDesc is the grpc.ServiceDesc for BitfsSellerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BitfsSellerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bitfs.v1.BitfsSellerService",
	HandlerType: (*BitfsSellerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _BitfsSellerService_Deliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bitfs/transfer.proto",
}
