import {mkdir, readFile, rm, writeFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';

await rm('generated-api', {recursive: true, force: true});
await mkdir('generated-api', {recursive: true});
await writeFile('generated-api/index.md', `---\nid: index\ntitle: API Reference\nsidebar_position: 1\n---\n\nThe API reference is generated from the exported Go packages and English doc comments before every build. It is the English source of truth; translated guides explain usage in each supported language.\n`);

const packages = ['bitfs', 'pool', 'buyer', 'seller', 'arbitration', 'wire'];
const run = (pkg) => new Promise((resolve, reject) => {
  const child = spawn('go', ['run', '-mod=mod', 'github.com/princjef/gomarkdoc/cmd/gomarkdoc@v1.1.0', '-o', `generated-api/${pkg}.md`, `github.com/bsv8/go-bitfs/${pkg}`], {stdio: 'inherit', env: {...process.env, GOWORK: 'off', GOFLAGS: ''}});
  child.on('exit', (code) => code === 0 ? resolve() : reject(new Error(`gomarkdoc failed for ${pkg} (${code})`)));
  child.on('error', reject);
});
for (const pkg of packages) {
  await run(pkg);
  const path = `generated-api/${pkg}.md`;
  const markdown = await readFile(path, 'utf8');
  // gomarkdoc emits HTML `name` anchors immediately before Markdown headings.
  // Docusaurus validates heading IDs, so move each generated name into the
  // supported explicit-heading-ID syntax and discard non-heading name anchors.
  const withHeadingIds = markdown
    .replace(/<a name="([^"]+)"><\/a>\r?\n(#{2,6} [^\n]+)/g, '$2 {#$1}')
    .replace(/<a name="[^"]+"><\/a>/g, '')
    .replace(/^## Index$/m, '## Index {#index}')
    .replace(/^## Constants$/m, '## Constants {#constants}')
    .replace(/^## Variables$/m, '## Variables {#variables}');
  await writeFile(path, withHeadingIds);
}

// The API pages are generated from Go comments, so their Chinese pages must
// also be regenerated from the same bytes on every build. The catalog is
// committed source; a missing entry is an error rather than an untranslated
// page, which makes a newly added exported comment visible during CI.
const catalog = JSON.parse(await readFile('api-translations.json', 'utf8'));
const translatedDir = 'i18n/zh-CN/docusaurus-plugin-content-docs-api/current';
await rm(translatedDir, {recursive: true, force: true});
await mkdir(translatedDir, {recursive: true});
const usedCatalogKeys = new Set();

const normalizeProse = (line) => line
  .replace(/\\([\\()[\]_*#])/g, '$1')
  .replace(/\\-/g, '-');

const translateHeading = (line) => {
  if (line === '## Index' || line === '## Index {#index}') return '## 索引 {#index}';
  if (line === '## Constants' || line === '## Constants {#constants}') return '## 常量 {#constants}';
  if (line === '## Variables' || line === '## Variables {#variables}') return '## 变量 {#variables}';
  if (line.startsWith('## type ')) return `## 类型 ${line.slice('## type '.length)}`;
  if (line.startsWith('## func ')) return `## 函数 ${line.slice('## func '.length)}`;
  if (line.startsWith('### func ')) return `### 函数 ${line.slice('### func '.length)}`;
  return line;
};

const translateIndexItem = (line) => line
  .replace(/^(\s*- \[)type(\b)/, '$1类型$2')
  .replace(/^(\s*- \[)func(\b)/, '$1函数$2')
  .replace(/^(\s*- \[)Constants(\])/, '$1常量$2')
  .replace(/^(\s*- \[)Variables(\])/, '$1变量$2');

const translateMarkdown = (markdown, sourceName) => {
  let inCode = false;
  let inIndex = false;
  const missing = [];
  const lines = markdown.split('\n').map((line) => {
    if (line.startsWith('```')) {
      inCode = !inCode;
      return line;
    }
    if (inCode || line.startsWith('<!--') || line.trim() === '') return line;
    if (line === '---' || line.startsWith('id: ') || line.startsWith('sidebar_position: ')) return line;
    if (line === 'title: API Reference') return 'title: API 参考';
    if (line.startsWith('#') && !line.startsWith('<!--')) {
      inIndex = line === '## Index' || line === '## Index {#index}';
      return translateHeading(line);
    }
    if (inIndex && /^\s*- /.test(line)) return translateIndexItem(line);
    if (line.startsWith('Generated by ')) return line.replace('Generated by ', '由 ').replace(/\)$/, ') 生成');
    const key = normalizeProse(line);
    if (Object.prototype.hasOwnProperty.call(catalog, key)) {
      usedCatalogKeys.add(key);
      return catalog[key];
    }
    missing.push({sourceName, line});
    return line;
  });
  if (missing.length) {
    const details = missing.map(({sourceName: name, line}) => `${name}: ${line}`).join('\n');
    throw new Error(`Missing Chinese API translations:\n${details}`);
  }
  return lines.join('\n');
};

const anchorIds = (markdown) => [...markdown.matchAll(/\{#([^}]+)\}/g)].map((match) => match[1]).sort();
const fencedBlocks = (markdown) => {
  const blocks = [];
  const lines = markdown.split('\n');
  for (let index = 0; index < lines.length; index += 1) {
    if (!lines[index].startsWith('```')) continue;
    const start = index;
    index += 1;
    while (index < lines.length && !lines[index].startsWith('```')) index += 1;
    if (index >= lines.length) throw new Error('Unclosed code fence in generated API markdown');
    blocks.push(lines.slice(start, index + 1).join('\n'));
  }
  return blocks;
};

for (const pkg of ['index', ...packages]) {
  const source = await readFile(`generated-api/${pkg}.md`, 'utf8');
  const translated = translateMarkdown(source, pkg);
  if (JSON.stringify(anchorIds(source)) !== JSON.stringify(anchorIds(translated))) {
    throw new Error(`Anchor IDs differ between English and Chinese API: ${pkg}`);
  }
  if (JSON.stringify(fencedBlocks(source)) !== JSON.stringify(fencedBlocks(translated))) {
    throw new Error(`Code blocks differ between English and Chinese API: ${pkg}`);
  }
  await writeFile(`${translatedDir}/${pkg}.md`, translated);
}
const unused = Object.keys(catalog).filter((key) => !usedCatalogKeys.has(key));
if (unused.length) throw new Error(`Unused Chinese API translations (source comments may have changed):\n${unused.join('\n')}`);
