// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/pool2of3/arbiter.proto

package pool2of3pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArbitrateSessionPoolRequestV1 是仲裁方对具体费用池的终态收尾请求。
type ArbitrateSessionPoolRequestV1 struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid                 string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	Approved                  bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason                    string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ArbiterSignature          []byte                 `protobuf:"bytes,4,opt,name=arbiter_signature,json=arbiterSignature,proto3" json:"arbiter_signature,omitempty"`
	FinalPayoutSat            uint64                 `protobuf:"varint,5,opt,name=final_payout_sat,json=finalPayoutSat,proto3" json:"final_payout_sat,omitempty"`
	ArbiterSignatureOnCloseTx []byte                 `protobuf:"bytes,6,opt,name=arbiter_signature_on_close_tx,json=arbiterSignatureOnCloseTx,proto3" json:"arbiter_signature_on_close_tx,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ArbitrateSessionPoolRequestV1) Reset() {
	*x = ArbitrateSessionPoolRequestV1{}
	mi := &file_proto_pool2of3_arbiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitrateSessionPoolRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrateSessionPoolRequestV1) ProtoMessage() {}

func (x *ArbitrateSessionPoolRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_arbiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitrateSessionPoolRequestV1.ProtoReflect.Descriptor instead.
func (*ArbitrateSessionPoolRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_arbiter_proto_rawDescGZIP(), []int{0}
}

func (x *ArbitrateSessionPoolRequestV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

func (x *ArbitrateSessionPoolRequestV1) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ArbitrateSessionPoolRequestV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ArbitrateSessionPoolRequestV1) GetArbiterSignature() []byte {
	if x != nil {
		return x.ArbiterSignature
	}
	return nil
}

func (x *ArbitrateSessionPoolRequestV1) GetFinalPayoutSat() uint64 {
	if x != nil {
		return x.FinalPayoutSat
	}
	return 0
}

func (x *ArbitrateSessionPoolRequestV1) GetArbiterSignatureOnCloseTx() []byte {
	if x != nil {
		return x.ArbiterSignatureOnCloseTx
	}
	return nil
}

// ArbitrateSessionPoolResponseV1 支持两阶段 close：先返回 sighash，
// 再由仲裁方提交 close tx 签名并返回完整可广播交易。
type ArbitrateSessionPoolResponseV1 struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClosingTxid           string                 `protobuf:"bytes,2,opt,name=closing_txid,json=closingTxid,proto3" json:"closing_txid,omitempty"`
	ClosingTxHex          string                 `protobuf:"bytes,3,opt,name=closing_tx_hex,json=closingTxHex,proto3" json:"closing_tx_hex,omitempty"`
	UnsignedCloseTxHex    string                 `protobuf:"bytes,4,opt,name=unsigned_close_tx_hex,json=unsignedCloseTxHex,proto3" json:"unsigned_close_tx_hex,omitempty"`
	ClosingTxSighashHex   string                 `protobuf:"bytes,5,opt,name=closing_tx_sighash_hex,json=closingTxSighashHex,proto3" json:"closing_tx_sighash_hex,omitempty"`
	NeedsArbiterSignature bool                   `protobuf:"varint,6,opt,name=needs_arbiter_signature,json=needsArbiterSignature,proto3" json:"needs_arbiter_signature,omitempty"`
	Error                 *PoolErrorV1           `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ArbitrateSessionPoolResponseV1) Reset() {
	*x = ArbitrateSessionPoolResponseV1{}
	mi := &file_proto_pool2of3_arbiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitrateSessionPoolResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrateSessionPoolResponseV1) ProtoMessage() {}

func (x *ArbitrateSessionPoolResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_arbiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitrateSessionPoolResponseV1.ProtoReflect.Descriptor instead.
func (*ArbitrateSessionPoolResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_arbiter_proto_rawDescGZIP(), []int{1}
}

func (x *ArbitrateSessionPoolResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ArbitrateSessionPoolResponseV1) GetClosingTxid() string {
	if x != nil {
		return x.ClosingTxid
	}
	return ""
}

func (x *ArbitrateSessionPoolResponseV1) GetClosingTxHex() string {
	if x != nil {
		return x.ClosingTxHex
	}
	return ""
}

func (x *ArbitrateSessionPoolResponseV1) GetUnsignedCloseTxHex() string {
	if x != nil {
		return x.UnsignedCloseTxHex
	}
	return ""
}

func (x *ArbitrateSessionPoolResponseV1) GetClosingTxSighashHex() string {
	if x != nil {
		return x.ClosingTxSighashHex
	}
	return ""
}

func (x *ArbitrateSessionPoolResponseV1) GetNeedsArbiterSignature() bool {
	if x != nil {
		return x.NeedsArbiterSignature
	}
	return false
}

func (x *ArbitrateSessionPoolResponseV1) GetError() *PoolErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_pool2of3_arbiter_proto protoreflect.FileDescriptor

const file_proto_pool2of3_arbiter_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/pool2of3/arbiter.proto\x12\vpool2of3.v1\x1a\x1bproto/pool2of3/common.proto\"\x8b\x02\n" +
	"\x1dArbitrateSessionPoolRequestV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12+\n" +
	"\x11arbiter_signature\x18\x04 \x01(\fR\x10arbiterSignature\x12(\n" +
	"\x10final_payout_sat\x18\x05 \x01(\x04R\x0efinalPayoutSat\x12@\n" +
	"\x1darbiter_signature_on_close_tx\x18\x06 \x01(\fR\x19arbiterSignatureOnCloseTx\"\xd3\x02\n" +
	"\x1eArbitrateSessionPoolResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fclosing_txid\x18\x02 \x01(\tR\vclosingTxid\x12$\n" +
	"\x0eclosing_tx_hex\x18\x03 \x01(\tR\fclosingTxHex\x121\n" +
	"\x15unsigned_close_tx_hex\x18\x04 \x01(\tR\x12unsignedCloseTxHex\x123\n" +
	"\x16closing_tx_sighash_hex\x18\x05 \x01(\tR\x13closingTxSighashHex\x126\n" +
	"\x17needs_arbiter_signature\x18\x06 \x01(\bR\x15needsArbiterSignature\x12.\n" +
	"\x05error\x18\a \x01(\v2\x18.pool2of3.v1.PoolErrorV1R\x05errorB6Z4github.com/bsv8/go-bitfs/proto/pool2of3pb;pool2of3pbb\x06proto3"

var (
	file_proto_pool2of3_arbiter_proto_rawDescOnce sync.Once
	file_proto_pool2of3_arbiter_proto_rawDescData []byte
)

func file_proto_pool2of3_arbiter_proto_rawDescGZIP() []byte {
	file_proto_pool2of3_arbiter_proto_rawDescOnce.Do(func() {
		file_proto_pool2of3_arbiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pool2of3_arbiter_proto_rawDesc), len(file_proto_pool2of3_arbiter_proto_rawDesc)))
	})
	return file_proto_pool2of3_arbiter_proto_rawDescData
}

var file_proto_pool2of3_arbiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pool2of3_arbiter_proto_goTypes = []any{
	(*ArbitrateSessionPoolRequestV1)(nil),  // 0: pool2of3.v1.ArbitrateSessionPoolRequestV1
	(*ArbitrateSessionPoolResponseV1)(nil), // 1: pool2of3.v1.ArbitrateSessionPoolResponseV1
	(*PoolErrorV1)(nil),                    // 2: pool2of3.v1.PoolErrorV1
}
var file_proto_pool2of3_arbiter_proto_depIdxs = []int32{
	2, // 0: pool2of3.v1.ArbitrateSessionPoolResponseV1.error:type_name -> pool2of3.v1.PoolErrorV1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pool2of3_arbiter_proto_init() }
func file_proto_pool2of3_arbiter_proto_init() {
	if File_proto_pool2of3_arbiter_proto != nil {
		return
	}
	file_proto_pool2of3_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pool2of3_arbiter_proto_rawDesc), len(file_proto_pool2of3_arbiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pool2of3_arbiter_proto_goTypes,
		DependencyIndexes: file_proto_pool2of3_arbiter_proto_depIdxs,
		MessageInfos:      file_proto_pool2of3_arbiter_proto_msgTypes,
	}.Build()
	File_proto_pool2of3_arbiter_proto = out.File
	file_proto_pool2of3_arbiter_proto_goTypes = nil
	file_proto_pool2of3_arbiter_proto_depIdxs = nil
}
