// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/pool2of3/common.proto

package pool2of3pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PoolSessionStateV1 int32

const (
	PoolSessionStateV1_POOL_SESSION_STATE_UNSPECIFIED PoolSessionStateV1 = 0
	PoolSessionStateV1_POOL_SESSION_STATE_OPENING     PoolSessionStateV1 = 1
	PoolSessionStateV1_POOL_SESSION_STATE_ACTIVE      PoolSessionStateV1 = 2
	PoolSessionStateV1_POOL_SESSION_STATE_UPDATING    PoolSessionStateV1 = 3
	PoolSessionStateV1_POOL_SESSION_STATE_DISPUTED    PoolSessionStateV1 = 4
	PoolSessionStateV1_POOL_SESSION_STATE_CLOSED      PoolSessionStateV1 = 5
	PoolSessionStateV1_POOL_SESSION_STATE_ARBITRATED  PoolSessionStateV1 = 6
)

// Enum value maps for PoolSessionStateV1.
var (
	PoolSessionStateV1_name = map[int32]string{
		0: "POOL_SESSION_STATE_UNSPECIFIED",
		1: "POOL_SESSION_STATE_OPENING",
		2: "POOL_SESSION_STATE_ACTIVE",
		3: "POOL_SESSION_STATE_UPDATING",
		4: "POOL_SESSION_STATE_DISPUTED",
		5: "POOL_SESSION_STATE_CLOSED",
		6: "POOL_SESSION_STATE_ARBITRATED",
	}
	PoolSessionStateV1_value = map[string]int32{
		"POOL_SESSION_STATE_UNSPECIFIED": 0,
		"POOL_SESSION_STATE_OPENING":     1,
		"POOL_SESSION_STATE_ACTIVE":      2,
		"POOL_SESSION_STATE_UPDATING":    3,
		"POOL_SESSION_STATE_DISPUTED":    4,
		"POOL_SESSION_STATE_CLOSED":      5,
		"POOL_SESSION_STATE_ARBITRATED":  6,
	}
)

func (x PoolSessionStateV1) Enum() *PoolSessionStateV1 {
	p := new(PoolSessionStateV1)
	*p = x
	return p
}

func (x PoolSessionStateV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolSessionStateV1) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pool2of3_common_proto_enumTypes[0].Descriptor()
}

func (PoolSessionStateV1) Type() protoreflect.EnumType {
	return &file_proto_pool2of3_common_proto_enumTypes[0]
}

func (x PoolSessionStateV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolSessionStateV1.Descriptor instead.
func (PoolSessionStateV1) EnumDescriptor() ([]byte, []int) {
	return file_proto_pool2of3_common_proto_rawDescGZIP(), []int{0}
}

type PoolUpdateTxResultV1 int32

const (
	PoolUpdateTxResultV1_POOL_UPDATE_TX_RESULT_UNSPECIFIED PoolUpdateTxResultV1 = 0
	PoolUpdateTxResultV1_POOL_UPDATE_TX_RESULT_COMMITTED   PoolUpdateTxResultV1 = 1
	PoolUpdateTxResultV1_POOL_UPDATE_TX_RESULT_REJECTED    PoolUpdateTxResultV1 = 2
)

// Enum value maps for PoolUpdateTxResultV1.
var (
	PoolUpdateTxResultV1_name = map[int32]string{
		0: "POOL_UPDATE_TX_RESULT_UNSPECIFIED",
		1: "POOL_UPDATE_TX_RESULT_COMMITTED",
		2: "POOL_UPDATE_TX_RESULT_REJECTED",
	}
	PoolUpdateTxResultV1_value = map[string]int32{
		"POOL_UPDATE_TX_RESULT_UNSPECIFIED": 0,
		"POOL_UPDATE_TX_RESULT_COMMITTED":   1,
		"POOL_UPDATE_TX_RESULT_REJECTED":    2,
	}
)

func (x PoolUpdateTxResultV1) Enum() *PoolUpdateTxResultV1 {
	p := new(PoolUpdateTxResultV1)
	*p = x
	return p
}

func (x PoolUpdateTxResultV1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolUpdateTxResultV1) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pool2of3_common_proto_enumTypes[1].Descriptor()
}

func (PoolUpdateTxResultV1) Type() protoreflect.EnumType {
	return &file_proto_pool2of3_common_proto_enumTypes[1]
}

func (x PoolUpdateTxResultV1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolUpdateTxResultV1.Descriptor instead.
func (PoolUpdateTxResultV1) EnumDescriptor() ([]byte, []int) {
	return file_proto_pool2of3_common_proto_rawDescGZIP(), []int{1}
}

// PoolErrorV1 是费用池对外稳定错误对象。
type PoolErrorV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolErrorV1) Reset() {
	*x = PoolErrorV1{}
	mi := &file_proto_pool2of3_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolErrorV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolErrorV1) ProtoMessage() {}

func (x *PoolErrorV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolErrorV1.ProtoReflect.Descriptor instead.
func (*PoolErrorV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_common_proto_rawDescGZIP(), []int{0}
}

func (x *PoolErrorV1) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PoolErrorV1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PoolSessionRefV1 按 spend_txid 标识一条 2-of-3 费用池。
// BitFS session_id 不进入本层；业务侧自行维护映射。
type PoolSessionRefV1 struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid           string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	BaseTxid            string                 `protobuf:"bytes,2,opt,name=base_txid,json=baseTxid,proto3" json:"base_txid,omitempty"`
	CurrentTxHex        string                 `protobuf:"bytes,3,opt,name=current_tx_hex,json=currentTxHex,proto3" json:"current_tx_hex,omitempty"`
	FinalTxid           string                 `protobuf:"bytes,4,opt,name=final_txid,json=finalTxid,proto3" json:"final_txid,omitempty"`
	BuyerPubkey         []byte                 `protobuf:"bytes,5,opt,name=buyer_pubkey,json=buyerPubkey,proto3" json:"buyer_pubkey,omitempty"`
	SellerPubkey        []byte                 `protobuf:"bytes,6,opt,name=seller_pubkey,json=sellerPubkey,proto3" json:"seller_pubkey,omitempty"`
	ArbiterPubkey       []byte                 `protobuf:"bytes,7,opt,name=arbiter_pubkey,json=arbiterPubkey,proto3" json:"arbiter_pubkey,omitempty"`
	RootSeedHash        []byte                 `protobuf:"bytes,8,opt,name=root_seed_hash,json=rootSeedHash,proto3" json:"root_seed_hash,omitempty"`
	State               PoolSessionStateV1     `protobuf:"varint,9,opt,name=state,proto3,enum=pool2of3.v1.PoolSessionStateV1" json:"state,omitempty"`
	BalanceSatoshi      uint64                 `protobuf:"varint,10,opt,name=balance_satoshi,json=balanceSatoshi,proto3" json:"balance_satoshi,omitempty"`
	CurrentServerAmount uint64                 `protobuf:"varint,11,opt,name=current_server_amount,json=currentServerAmount,proto3" json:"current_server_amount,omitempty"`
	CurrentClientAmount uint64                 `protobuf:"varint,12,opt,name=current_client_amount,json=currentClientAmount,proto3" json:"current_client_amount,omitempty"`
	Sequence            uint32                 `protobuf:"varint,13,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CreatedAtUnix       int64                  `protobuf:"varint,14,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix       int64                  `protobuf:"varint,15,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	ServiceDeadlineUnix int64                  `protobuf:"varint,16,opt,name=service_deadline_unix,json=serviceDeadlineUnix,proto3" json:"service_deadline_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PoolSessionRefV1) Reset() {
	*x = PoolSessionRefV1{}
	mi := &file_proto_pool2of3_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolSessionRefV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolSessionRefV1) ProtoMessage() {}

func (x *PoolSessionRefV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolSessionRefV1.ProtoReflect.Descriptor instead.
func (*PoolSessionRefV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_common_proto_rawDescGZIP(), []int{1}
}

func (x *PoolSessionRefV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

func (x *PoolSessionRefV1) GetBaseTxid() string {
	if x != nil {
		return x.BaseTxid
	}
	return ""
}

func (x *PoolSessionRefV1) GetCurrentTxHex() string {
	if x != nil {
		return x.CurrentTxHex
	}
	return ""
}

func (x *PoolSessionRefV1) GetFinalTxid() string {
	if x != nil {
		return x.FinalTxid
	}
	return ""
}

func (x *PoolSessionRefV1) GetBuyerPubkey() []byte {
	if x != nil {
		return x.BuyerPubkey
	}
	return nil
}

func (x *PoolSessionRefV1) GetSellerPubkey() []byte {
	if x != nil {
		return x.SellerPubkey
	}
	return nil
}

func (x *PoolSessionRefV1) GetArbiterPubkey() []byte {
	if x != nil {
		return x.ArbiterPubkey
	}
	return nil
}

func (x *PoolSessionRefV1) GetRootSeedHash() []byte {
	if x != nil {
		return x.RootSeedHash
	}
	return nil
}

func (x *PoolSessionRefV1) GetState() PoolSessionStateV1 {
	if x != nil {
		return x.State
	}
	return PoolSessionStateV1_POOL_SESSION_STATE_UNSPECIFIED
}

func (x *PoolSessionRefV1) GetBalanceSatoshi() uint64 {
	if x != nil {
		return x.BalanceSatoshi
	}
	return 0
}

func (x *PoolSessionRefV1) GetCurrentServerAmount() uint64 {
	if x != nil {
		return x.CurrentServerAmount
	}
	return 0
}

func (x *PoolSessionRefV1) GetCurrentClientAmount() uint64 {
	if x != nil {
		return x.CurrentClientAmount
	}
	return 0
}

func (x *PoolSessionRefV1) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PoolSessionRefV1) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *PoolSessionRefV1) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *PoolSessionRefV1) GetServiceDeadlineUnix() int64 {
	if x != nil {
		return x.ServiceDeadlineUnix
	}
	return 0
}

var File_proto_pool2of3_common_proto protoreflect.FileDescriptor

const file_proto_pool2of3_common_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/pool2of3/common.proto\x12\vpool2of3.v1\";\n" +
	"\vPoolErrorV1\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x05\n" +
	"\x10PoolSessionRefV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\x12\x1b\n" +
	"\tbase_txid\x18\x02 \x01(\tR\bbaseTxid\x12$\n" +
	"\x0ecurrent_tx_hex\x18\x03 \x01(\tR\fcurrentTxHex\x12\x1d\n" +
	"\n" +
	"final_txid\x18\x04 \x01(\tR\tfinalTxid\x12!\n" +
	"\fbuyer_pubkey\x18\x05 \x01(\fR\vbuyerPubkey\x12#\n" +
	"\rseller_pubkey\x18\x06 \x01(\fR\fsellerPubkey\x12%\n" +
	"\x0earbiter_pubkey\x18\a \x01(\fR\rarbiterPubkey\x12$\n" +
	"\x0eroot_seed_hash\x18\b \x01(\fR\frootSeedHash\x125\n" +
	"\x05state\x18\t \x01(\x0e2\x1f.pool2of3.v1.PoolSessionStateV1R\x05state\x12'\n" +
	"\x0fbalance_satoshi\x18\n" +
	" \x01(\x04R\x0ebalanceSatoshi\x122\n" +
	"\x15current_server_amount\x18\v \x01(\x04R\x13currentServerAmount\x122\n" +
	"\x15current_client_amount\x18\f \x01(\x04R\x13currentClientAmount\x12\x1a\n" +
	"\bsequence\x18\r \x01(\rR\bsequence\x12&\n" +
	"\x0fcreated_at_unix\x18\x0e \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x0f \x01(\x03R\rupdatedAtUnix\x122\n" +
	"\x15service_deadline_unix\x18\x10 \x01(\x03R\x13serviceDeadlineUnix*\xfb\x01\n" +
	"\x12PoolSessionStateV1\x12\"\n" +
	"\x1ePOOL_SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPOOL_SESSION_STATE_OPENING\x10\x01\x12\x1d\n" +
	"\x19POOL_SESSION_STATE_ACTIVE\x10\x02\x12\x1f\n" +
	"\x1bPOOL_SESSION_STATE_UPDATING\x10\x03\x12\x1f\n" +
	"\x1bPOOL_SESSION_STATE_DISPUTED\x10\x04\x12\x1d\n" +
	"\x19POOL_SESSION_STATE_CLOSED\x10\x05\x12!\n" +
	"\x1dPOOL_SESSION_STATE_ARBITRATED\x10\x06*\x86\x01\n" +
	"\x14PoolUpdateTxResultV1\x12%\n" +
	"!POOL_UPDATE_TX_RESULT_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fPOOL_UPDATE_TX_RESULT_COMMITTED\x10\x01\x12\"\n" +
	"\x1ePOOL_UPDATE_TX_RESULT_REJECTED\x10\x02B6Z4github.com/bsv8/go-bitfs/proto/pool2of3pb;pool2of3pbb\x06proto3"

var (
	file_proto_pool2of3_common_proto_rawDescOnce sync.Once
	file_proto_pool2of3_common_proto_rawDescData []byte
)

func file_proto_pool2of3_common_proto_rawDescGZIP() []byte {
	file_proto_pool2of3_common_proto_rawDescOnce.Do(func() {
		file_proto_pool2of3_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pool2of3_common_proto_rawDesc), len(file_proto_pool2of3_common_proto_rawDesc)))
	})
	return file_proto_pool2of3_common_proto_rawDescData
}

var file_proto_pool2of3_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_pool2of3_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pool2of3_common_proto_goTypes = []any{
	(PoolSessionStateV1)(0),   // 0: pool2of3.v1.PoolSessionStateV1
	(PoolUpdateTxResultV1)(0), // 1: pool2of3.v1.PoolUpdateTxResultV1
	(*PoolErrorV1)(nil),       // 2: pool2of3.v1.PoolErrorV1
	(*PoolSessionRefV1)(nil),  // 3: pool2of3.v1.PoolSessionRefV1
}
var file_proto_pool2of3_common_proto_depIdxs = []int32{
	0, // 0: pool2of3.v1.PoolSessionRefV1.state:type_name -> pool2of3.v1.PoolSessionStateV1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pool2of3_common_proto_init() }
func file_proto_pool2of3_common_proto_init() {
	if File_proto_pool2of3_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pool2of3_common_proto_rawDesc), len(file_proto_pool2of3_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pool2of3_common_proto_goTypes,
		DependencyIndexes: file_proto_pool2of3_common_proto_depIdxs,
		EnumInfos:         file_proto_pool2of3_common_proto_enumTypes,
		MessageInfos:      file_proto_pool2of3_common_proto_msgTypes,
	}.Build()
	File_proto_pool2of3_common_proto = out.File
	file_proto_pool2of3_common_proto_goTypes = nil
	file_proto_pool2of3_common_proto_depIdxs = nil
}
