// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/pool2of3/session.proto

package pool2of3pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolSessionService_EnsureSessionPool_FullMethodName    = "/pool2of3.v1.PoolSessionService/EnsureSessionPool"
	PoolSessionService_GetSessionPool_FullMethodName       = "/pool2of3.v1.PoolSessionService/GetSessionPool"
	PoolSessionService_PrepareTicketPayment_FullMethodName = "/pool2of3.v1.PoolSessionService/PrepareTicketPayment"
	PoolSessionService_CommitTicketPayment_FullMethodName  = "/pool2of3.v1.PoolSessionService/CommitTicketPayment"
	PoolSessionService_AbortTicketPayment_FullMethodName   = "/pool2of3.v1.PoolSessionService/AbortTicketPayment"
	PoolSessionService_CloseSessionPool_FullMethodName     = "/pool2of3.v1.PoolSessionService/CloseSessionPool"
	PoolSessionService_ArbitrateSessionPool_FullMethodName = "/pool2of3.v1.PoolSessionService/ArbitrateSessionPool"
)

// PoolSessionServiceClient is the client API for PoolSessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PoolSessionService 是 BitFS 正式交易使用的 2-of-3 费用池服务。
type PoolSessionServiceClient interface {
	EnsureSessionPool(ctx context.Context, in *EnsureSessionPoolRequestV1, opts ...grpc.CallOption) (*EnsureSessionPoolResponseV1, error)
	GetSessionPool(ctx context.Context, in *GetSessionPoolRequestV1, opts ...grpc.CallOption) (*GetSessionPoolResponseV1, error)
	PrepareTicketPayment(ctx context.Context, in *PrepareTicketPaymentRequestV1, opts ...grpc.CallOption) (*PrepareTicketPaymentResponseV1, error)
	CommitTicketPayment(ctx context.Context, in *CommitTicketPaymentRequestV1, opts ...grpc.CallOption) (*CommitTicketPaymentResponseV1, error)
	AbortTicketPayment(ctx context.Context, in *AbortTicketPaymentRequestV1, opts ...grpc.CallOption) (*AbortTicketPaymentResponseV1, error)
	CloseSessionPool(ctx context.Context, in *CloseSessionPoolRequestV1, opts ...grpc.CallOption) (*CloseSessionPoolResponseV1, error)
	ArbitrateSessionPool(ctx context.Context, in *ArbitrateSessionPoolRequestV1, opts ...grpc.CallOption) (*ArbitrateSessionPoolResponseV1, error)
}

type poolSessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolSessionServiceClient(cc grpc.ClientConnInterface) PoolSessionServiceClient {
	return &poolSessionServiceClient{cc}
}

func (c *poolSessionServiceClient) EnsureSessionPool(ctx context.Context, in *EnsureSessionPoolRequestV1, opts ...grpc.CallOption) (*EnsureSessionPoolResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureSessionPoolResponseV1)
	err := c.cc.Invoke(ctx, PoolSessionService_EnsureSessionPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolSessionServiceClient) GetSessionPool(ctx context.Context, in *GetSessionPoolRequestV1, opts ...grpc.CallOption) (*GetSessionPoolResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionPoolResponseV1)
	err := c.cc.Invoke(ctx, PoolSessionService_GetSessionPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolSessionServiceClient) PrepareTicketPayment(ctx context.Context, in *PrepareTicketPaymentRequestV1, opts ...grpc.CallOption) (*PrepareTicketPaymentResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTicketPaymentResponseV1)
	err := c.cc.Invoke(ctx, PoolSessionService_PrepareTicketPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolSessionServiceClient) CommitTicketPayment(ctx context.Context, in *CommitTicketPaymentRequestV1, opts ...grpc.CallOption) (*CommitTicketPaymentResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitTicketPaymentResponseV1)
	err := c.cc.Invoke(ctx, PoolSessionService_CommitTicketPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolSessionServiceClient) AbortTicketPayment(ctx context.Context, in *AbortTicketPaymentRequestV1, opts ...grpc.CallOption) (*AbortTicketPaymentResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortTicketPaymentResponseV1)
	err := c.cc.Invoke(ctx, PoolSessionService_AbortTicketPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolSessionServiceClient) CloseSessionPool(ctx context.Context, in *CloseSessionPoolRequestV1, opts ...grpc.CallOption) (*CloseSessionPoolResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionPoolResponseV1)
	err := c.cc.Invoke(ctx, PoolSessionService_CloseSessionPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolSessionServiceClient) ArbitrateSessionPool(ctx context.Context, in *ArbitrateSessionPoolRequestV1, opts ...grpc.CallOption) (*ArbitrateSessionPoolResponseV1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArbitrateSessionPoolResponseV1)
	err := c.cc.Invoke(ctx, PoolSessionService_ArbitrateSessionPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolSessionServiceServer is the server API for PoolSessionService service.
// All implementations must embed UnimplementedPoolSessionServiceServer
// for forward compatibility.
//
// PoolSessionService 是 BitFS 正式交易使用的 2-of-3 费用池服务。
type PoolSessionServiceServer interface {
	EnsureSessionPool(context.Context, *EnsureSessionPoolRequestV1) (*EnsureSessionPoolResponseV1, error)
	GetSessionPool(context.Context, *GetSessionPoolRequestV1) (*GetSessionPoolResponseV1, error)
	PrepareTicketPayment(context.Context, *PrepareTicketPaymentRequestV1) (*PrepareTicketPaymentResponseV1, error)
	CommitTicketPayment(context.Context, *CommitTicketPaymentRequestV1) (*CommitTicketPaymentResponseV1, error)
	AbortTicketPayment(context.Context, *AbortTicketPaymentRequestV1) (*AbortTicketPaymentResponseV1, error)
	CloseSessionPool(context.Context, *CloseSessionPoolRequestV1) (*CloseSessionPoolResponseV1, error)
	ArbitrateSessionPool(context.Context, *ArbitrateSessionPoolRequestV1) (*ArbitrateSessionPoolResponseV1, error)
	mustEmbedUnimplementedPoolSessionServiceServer()
}

// UnimplementedPoolSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolSessionServiceServer struct{}

func (UnimplementedPoolSessionServiceServer) EnsureSessionPool(context.Context, *EnsureSessionPoolRequestV1) (*EnsureSessionPoolResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureSessionPool not implemented")
}
func (UnimplementedPoolSessionServiceServer) GetSessionPool(context.Context, *GetSessionPoolRequestV1) (*GetSessionPoolResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionPool not implemented")
}
func (UnimplementedPoolSessionServiceServer) PrepareTicketPayment(context.Context, *PrepareTicketPaymentRequestV1) (*PrepareTicketPaymentResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTicketPayment not implemented")
}
func (UnimplementedPoolSessionServiceServer) CommitTicketPayment(context.Context, *CommitTicketPaymentRequestV1) (*CommitTicketPaymentResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTicketPayment not implemented")
}
func (UnimplementedPoolSessionServiceServer) AbortTicketPayment(context.Context, *AbortTicketPaymentRequestV1) (*AbortTicketPaymentResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortTicketPayment not implemented")
}
func (UnimplementedPoolSessionServiceServer) CloseSessionPool(context.Context, *CloseSessionPoolRequestV1) (*CloseSessionPoolResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSessionPool not implemented")
}
func (UnimplementedPoolSessionServiceServer) ArbitrateSessionPool(context.Context, *ArbitrateSessionPoolRequestV1) (*ArbitrateSessionPoolResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArbitrateSessionPool not implemented")
}
func (UnimplementedPoolSessionServiceServer) mustEmbedUnimplementedPoolSessionServiceServer() {}
func (UnimplementedPoolSessionServiceServer) testEmbeddedByValue()                            {}

// UnsafePoolSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolSessionServiceServer will
// result in compilation errors.
type UnsafePoolSessionServiceServer interface {
	mustEmbedUnimplementedPoolSessionServiceServer()
}

func RegisterPoolSessionServiceServer(s grpc.ServiceRegistrar, srv PoolSessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedPoolSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolSessionService_ServiceDesc, srv)
}

func _PoolSessionService_EnsureSessionPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureSessionPoolRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolSessionServiceServer).EnsureSessionPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolSessionService_EnsureSessionPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolSessionServiceServer).EnsureSessionPool(ctx, req.(*EnsureSessionPoolRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolSessionService_GetSessionPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionPoolRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolSessionServiceServer).GetSessionPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolSessionService_GetSessionPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolSessionServiceServer).GetSessionPool(ctx, req.(*GetSessionPoolRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolSessionService_PrepareTicketPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTicketPaymentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolSessionServiceServer).PrepareTicketPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolSessionService_PrepareTicketPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolSessionServiceServer).PrepareTicketPayment(ctx, req.(*PrepareTicketPaymentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolSessionService_CommitTicketPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTicketPaymentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolSessionServiceServer).CommitTicketPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolSessionService_CommitTicketPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolSessionServiceServer).CommitTicketPayment(ctx, req.(*CommitTicketPaymentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolSessionService_AbortTicketPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortTicketPaymentRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolSessionServiceServer).AbortTicketPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolSessionService_AbortTicketPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolSessionServiceServer).AbortTicketPayment(ctx, req.(*AbortTicketPaymentRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolSessionService_CloseSessionPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionPoolRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolSessionServiceServer).CloseSessionPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolSessionService_CloseSessionPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolSessionServiceServer).CloseSessionPool(ctx, req.(*CloseSessionPoolRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolSessionService_ArbitrateSessionPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArbitrateSessionPoolRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolSessionServiceServer).ArbitrateSessionPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolSessionService_ArbitrateSessionPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolSessionServiceServer).ArbitrateSessionPool(ctx, req.(*ArbitrateSessionPoolRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolSessionService_ServiceDesc is the grpc.ServiceDesc for PoolSessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolSessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pool2of3.v1.PoolSessionService",
	HandlerType: (*PoolSessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureSessionPool",
			Handler:    _PoolSessionService_EnsureSessionPool_Handler,
		},
		{
			MethodName: "GetSessionPool",
			Handler:    _PoolSessionService_GetSessionPool_Handler,
		},
		{
			MethodName: "PrepareTicketPayment",
			Handler:    _PoolSessionService_PrepareTicketPayment_Handler,
		},
		{
			MethodName: "CommitTicketPayment",
			Handler:    _PoolSessionService_CommitTicketPayment_Handler,
		},
		{
			MethodName: "AbortTicketPayment",
			Handler:    _PoolSessionService_AbortTicketPayment_Handler,
		},
		{
			MethodName: "CloseSessionPool",
			Handler:    _PoolSessionService_CloseSessionPool_Handler,
		},
		{
			MethodName: "ArbitrateSessionPool",
			Handler:    _PoolSessionService_ArbitrateSessionPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pool2of3/session.proto",
}
