// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/pool2of3/session.proto

package pool2of3pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PoolTicketRefV1 是付款层对一张 BitFS 票据的幂等引用。
type PoolTicketRefV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid     string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	PriceSat      uint64                 `protobuf:"varint,4,opt,name=price_sat,json=priceSat,proto3" json:"price_sat,omitempty"`
	TicketId      string                 `protobuf:"bytes,5,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolTicketRefV1) Reset() {
	*x = PoolTicketRefV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolTicketRefV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolTicketRefV1) ProtoMessage() {}

func (x *PoolTicketRefV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolTicketRefV1.ProtoReflect.Descriptor instead.
func (*PoolTicketRefV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{0}
}

func (x *PoolTicketRefV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

func (x *PoolTicketRefV1) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PoolTicketRefV1) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *PoolTicketRefV1) GetPriceSat() uint64 {
	if x != nil {
		return x.PriceSat
	}
	return 0
}

func (x *PoolTicketRefV1) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type EnsureSessionPoolRequestV1 struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BuyerPubkey         []byte                 `protobuf:"bytes,1,opt,name=buyer_pubkey,json=buyerPubkey,proto3" json:"buyer_pubkey,omitempty"`
	SellerPubkey        []byte                 `protobuf:"bytes,2,opt,name=seller_pubkey,json=sellerPubkey,proto3" json:"seller_pubkey,omitempty"`
	ArbiterPubkey       []byte                 `protobuf:"bytes,3,opt,name=arbiter_pubkey,json=arbiterPubkey,proto3" json:"arbiter_pubkey,omitempty"`
	RootSeedHash        []byte                 `protobuf:"bytes,4,opt,name=root_seed_hash,json=rootSeedHash,proto3" json:"root_seed_hash,omitempty"`
	InitAmountSat       uint64                 `protobuf:"varint,5,opt,name=init_amount_sat,json=initAmountSat,proto3" json:"init_amount_sat,omitempty"`
	ServiceDeadlineUnix int64                  `protobuf:"varint,6,opt,name=service_deadline_unix,json=serviceDeadlineUnix,proto3" json:"service_deadline_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnsureSessionPoolRequestV1) Reset() {
	*x = EnsureSessionPoolRequestV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionPoolRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionPoolRequestV1) ProtoMessage() {}

func (x *EnsureSessionPoolRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionPoolRequestV1.ProtoReflect.Descriptor instead.
func (*EnsureSessionPoolRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureSessionPoolRequestV1) GetBuyerPubkey() []byte {
	if x != nil {
		return x.BuyerPubkey
	}
	return nil
}

func (x *EnsureSessionPoolRequestV1) GetSellerPubkey() []byte {
	if x != nil {
		return x.SellerPubkey
	}
	return nil
}

func (x *EnsureSessionPoolRequestV1) GetArbiterPubkey() []byte {
	if x != nil {
		return x.ArbiterPubkey
	}
	return nil
}

func (x *EnsureSessionPoolRequestV1) GetRootSeedHash() []byte {
	if x != nil {
		return x.RootSeedHash
	}
	return nil
}

func (x *EnsureSessionPoolRequestV1) GetInitAmountSat() uint64 {
	if x != nil {
		return x.InitAmountSat
	}
	return 0
}

func (x *EnsureSessionPoolRequestV1) GetServiceDeadlineUnix() int64 {
	if x != nil {
		return x.ServiceDeadlineUnix
	}
	return 0
}

type EnsureSessionPoolResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PoolSessionRefV1      `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Error         *PoolErrorV1           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureSessionPoolResponseV1) Reset() {
	*x = EnsureSessionPoolResponseV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureSessionPoolResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureSessionPoolResponseV1) ProtoMessage() {}

func (x *EnsureSessionPoolResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureSessionPoolResponseV1.ProtoReflect.Descriptor instead.
func (*EnsureSessionPoolResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{2}
}

func (x *EnsureSessionPoolResponseV1) GetSession() *PoolSessionRefV1 {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *EnsureSessionPoolResponseV1) GetError() *PoolErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSessionPoolRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid     string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionPoolRequestV1) Reset() {
	*x = GetSessionPoolRequestV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionPoolRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionPoolRequestV1) ProtoMessage() {}

func (x *GetSessionPoolRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionPoolRequestV1.ProtoReflect.Descriptor instead.
func (*GetSessionPoolRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionPoolRequestV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

type GetSessionPoolResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PoolSessionRefV1      `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Error         *PoolErrorV1           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionPoolResponseV1) Reset() {
	*x = GetSessionPoolResponseV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionPoolResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionPoolResponseV1) ProtoMessage() {}

func (x *GetSessionPoolResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionPoolResponseV1.ProtoReflect.Descriptor instead.
func (*GetSessionPoolResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionPoolResponseV1) GetSession() *PoolSessionRefV1 {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionPoolResponseV1) GetError() *PoolErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

type PrepareTicketPaymentRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid     string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	Ticket        *PoolTicketRefV1       `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareTicketPaymentRequestV1) Reset() {
	*x = PrepareTicketPaymentRequestV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTicketPaymentRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTicketPaymentRequestV1) ProtoMessage() {}

func (x *PrepareTicketPaymentRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTicketPaymentRequestV1.ProtoReflect.Descriptor instead.
func (*PrepareTicketPaymentRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareTicketPaymentRequestV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

func (x *PrepareTicketPaymentRequestV1) GetTicket() *PoolTicketRefV1 {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type PrepareTicketPaymentResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Error         *PoolErrorV1           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareTicketPaymentResponseV1) Reset() {
	*x = PrepareTicketPaymentResponseV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTicketPaymentResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTicketPaymentResponseV1) ProtoMessage() {}

func (x *PrepareTicketPaymentResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTicketPaymentResponseV1.ProtoReflect.Descriptor instead.
func (*PrepareTicketPaymentResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareTicketPaymentResponseV1) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *PrepareTicketPaymentResponseV1) GetError() *PoolErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

type CommitTicketPaymentRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid     string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	ProposalId    string                 `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Ticket        *PoolTicketRefV1       `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTicketPaymentRequestV1) Reset() {
	*x = CommitTicketPaymentRequestV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTicketPaymentRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTicketPaymentRequestV1) ProtoMessage() {}

func (x *CommitTicketPaymentRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTicketPaymentRequestV1.ProtoReflect.Descriptor instead.
func (*CommitTicketPaymentRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{7}
}

func (x *CommitTicketPaymentRequestV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

func (x *CommitTicketPaymentRequestV1) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *CommitTicketPaymentRequestV1) GetTicket() *PoolTicketRefV1 {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type CommitTicketPaymentResponseV1 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result            PoolUpdateTxResultV1   `protobuf:"varint,2,opt,name=result,proto3,enum=pool2of3.v1.PoolUpdateTxResultV1" json:"result,omitempty"`
	SequenceAfter     uint64                 `protobuf:"varint,3,opt,name=sequence_after,json=sequenceAfter,proto3" json:"sequence_after,omitempty"`
	ServerAmountAfter uint64                 `protobuf:"varint,4,opt,name=server_amount_after,json=serverAmountAfter,proto3" json:"server_amount_after,omitempty"`
	ClientAmountAfter uint64                 `protobuf:"varint,5,opt,name=client_amount_after,json=clientAmountAfter,proto3" json:"client_amount_after,omitempty"`
	Error             *PoolErrorV1           `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommitTicketPaymentResponseV1) Reset() {
	*x = CommitTicketPaymentResponseV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTicketPaymentResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTicketPaymentResponseV1) ProtoMessage() {}

func (x *CommitTicketPaymentResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTicketPaymentResponseV1.ProtoReflect.Descriptor instead.
func (*CommitTicketPaymentResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{8}
}

func (x *CommitTicketPaymentResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitTicketPaymentResponseV1) GetResult() PoolUpdateTxResultV1 {
	if x != nil {
		return x.Result
	}
	return PoolUpdateTxResultV1_POOL_UPDATE_TX_RESULT_UNSPECIFIED
}

func (x *CommitTicketPaymentResponseV1) GetSequenceAfter() uint64 {
	if x != nil {
		return x.SequenceAfter
	}
	return 0
}

func (x *CommitTicketPaymentResponseV1) GetServerAmountAfter() uint64 {
	if x != nil {
		return x.ServerAmountAfter
	}
	return 0
}

func (x *CommitTicketPaymentResponseV1) GetClientAmountAfter() uint64 {
	if x != nil {
		return x.ClientAmountAfter
	}
	return 0
}

func (x *CommitTicketPaymentResponseV1) GetError() *PoolErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

type AbortTicketPaymentRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid     string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	ProposalId    string                 `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Ticket        *PoolTicketRefV1       `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTicketPaymentRequestV1) Reset() {
	*x = AbortTicketPaymentRequestV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTicketPaymentRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTicketPaymentRequestV1) ProtoMessage() {}

func (x *AbortTicketPaymentRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTicketPaymentRequestV1.ProtoReflect.Descriptor instead.
func (*AbortTicketPaymentRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{9}
}

func (x *AbortTicketPaymentRequestV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

func (x *AbortTicketPaymentRequestV1) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *AbortTicketPaymentRequestV1) GetTicket() *PoolTicketRefV1 {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *AbortTicketPaymentRequestV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbortTicketPaymentResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *PoolErrorV1           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTicketPaymentResponseV1) Reset() {
	*x = AbortTicketPaymentResponseV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTicketPaymentResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTicketPaymentResponseV1) ProtoMessage() {}

func (x *AbortTicketPaymentResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTicketPaymentResponseV1.ProtoReflect.Descriptor instead.
func (*AbortTicketPaymentResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{10}
}

func (x *AbortTicketPaymentResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbortTicketPaymentResponseV1) GetError() *PoolErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

type CloseSessionPoolRequestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpendTxid     string                 `protobuf:"bytes,1,opt,name=spend_txid,json=spendTxid,proto3" json:"spend_txid,omitempty"`
	RefundAddress string                 `protobuf:"bytes,2,opt,name=refund_address,json=refundAddress,proto3" json:"refund_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionPoolRequestV1) Reset() {
	*x = CloseSessionPoolRequestV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionPoolRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionPoolRequestV1) ProtoMessage() {}

func (x *CloseSessionPoolRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionPoolRequestV1.ProtoReflect.Descriptor instead.
func (*CloseSessionPoolRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{11}
}

func (x *CloseSessionPoolRequestV1) GetSpendTxid() string {
	if x != nil {
		return x.SpendTxid
	}
	return ""
}

func (x *CloseSessionPoolRequestV1) GetRefundAddress() string {
	if x != nil {
		return x.RefundAddress
	}
	return ""
}

type CloseSessionPoolResponseV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ClosingTxid   string                 `protobuf:"bytes,2,opt,name=closing_txid,json=closingTxid,proto3" json:"closing_txid,omitempty"`
	ClosingTxHex  string                 `protobuf:"bytes,3,opt,name=closing_tx_hex,json=closingTxHex,proto3" json:"closing_tx_hex,omitempty"`
	Error         *PoolErrorV1           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionPoolResponseV1) Reset() {
	*x = CloseSessionPoolResponseV1{}
	mi := &file_proto_pool2of3_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionPoolResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionPoolResponseV1) ProtoMessage() {}

func (x *CloseSessionPoolResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pool2of3_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionPoolResponseV1.ProtoReflect.Descriptor instead.
func (*CloseSessionPoolResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_pool2of3_session_proto_rawDescGZIP(), []int{12}
}

func (x *CloseSessionPoolResponseV1) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseSessionPoolResponseV1) GetClosingTxid() string {
	if x != nil {
		return x.ClosingTxid
	}
	return ""
}

func (x *CloseSessionPoolResponseV1) GetClosingTxHex() string {
	if x != nil {
		return x.ClosingTxHex
	}
	return ""
}

func (x *CloseSessionPoolResponseV1) GetError() *PoolErrorV1 {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_pool2of3_session_proto protoreflect.FileDescriptor

const file_proto_pool2of3_session_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/pool2of3/session.proto\x12\vpool2of3.v1\x1a\x1cproto/pool2of3/arbiter.proto\x1a\x1bproto/pool2of3/common.proto\"\xa9\x01\n" +
	"\x0fPoolTicketRefV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\fR\vcontentHash\x12\x1b\n" +
	"\tprice_sat\x18\x04 \x01(\x04R\bpriceSat\x12\x1b\n" +
	"\tticket_id\x18\x05 \x01(\tR\bticketId\"\x8d\x02\n" +
	"\x1aEnsureSessionPoolRequestV1\x12!\n" +
	"\fbuyer_pubkey\x18\x01 \x01(\fR\vbuyerPubkey\x12#\n" +
	"\rseller_pubkey\x18\x02 \x01(\fR\fsellerPubkey\x12%\n" +
	"\x0earbiter_pubkey\x18\x03 \x01(\fR\rarbiterPubkey\x12$\n" +
	"\x0eroot_seed_hash\x18\x04 \x01(\fR\frootSeedHash\x12&\n" +
	"\x0finit_amount_sat\x18\x05 \x01(\x04R\rinitAmountSat\x122\n" +
	"\x15service_deadline_unix\x18\x06 \x01(\x03R\x13serviceDeadlineUnix\"\x86\x01\n" +
	"\x1bEnsureSessionPoolResponseV1\x127\n" +
	"\asession\x18\x01 \x01(\v2\x1d.pool2of3.v1.PoolSessionRefV1R\asession\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.pool2of3.v1.PoolErrorV1R\x05error\"8\n" +
	"\x17GetSessionPoolRequestV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\"\x83\x01\n" +
	"\x18GetSessionPoolResponseV1\x127\n" +
	"\asession\x18\x01 \x01(\v2\x1d.pool2of3.v1.PoolSessionRefV1R\asession\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.pool2of3.v1.PoolErrorV1R\x05error\"t\n" +
	"\x1dPrepareTicketPaymentRequestV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\x124\n" +
	"\x06ticket\x18\x02 \x01(\v2\x1c.pool2of3.v1.PoolTicketRefV1R\x06ticket\"q\n" +
	"\x1ePrepareTicketPaymentResponseV1\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.pool2of3.v1.PoolErrorV1R\x05error\"\x94\x01\n" +
	"\x1cCommitTicketPaymentRequestV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\tR\n" +
	"proposalId\x124\n" +
	"\x06ticket\x18\x03 \x01(\v2\x1c.pool2of3.v1.PoolTicketRefV1R\x06ticket\"\xab\x02\n" +
	"\x1dCommitTicketPaymentResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\x06result\x18\x02 \x01(\x0e2!.pool2of3.v1.PoolUpdateTxResultV1R\x06result\x12%\n" +
	"\x0esequence_after\x18\x03 \x01(\x04R\rsequenceAfter\x12.\n" +
	"\x13server_amount_after\x18\x04 \x01(\x04R\x11serverAmountAfter\x12.\n" +
	"\x13client_amount_after\x18\x05 \x01(\x04R\x11clientAmountAfter\x12.\n" +
	"\x05error\x18\x06 \x01(\v2\x18.pool2of3.v1.PoolErrorV1R\x05error\"\xab\x01\n" +
	"\x1bAbortTicketPaymentRequestV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\tR\n" +
	"proposalId\x124\n" +
	"\x06ticket\x18\x03 \x01(\v2\x1c.pool2of3.v1.PoolTicketRefV1R\x06ticket\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"h\n" +
	"\x1cAbortTicketPaymentResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x18.pool2of3.v1.PoolErrorV1R\x05error\"a\n" +
	"\x19CloseSessionPoolRequestV1\x12\x1d\n" +
	"\n" +
	"spend_txid\x18\x01 \x01(\tR\tspendTxid\x12%\n" +
	"\x0erefund_address\x18\x02 \x01(\tR\rrefundAddress\"\xaf\x01\n" +
	"\x1aCloseSessionPoolResponseV1\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fclosing_txid\x18\x02 \x01(\tR\vclosingTxid\x12$\n" +
	"\x0eclosing_tx_hex\x18\x03 \x01(\tR\fclosingTxHex\x12.\n" +
	"\x05error\x18\x04 \x01(\v2\x18.pool2of3.v1.PoolErrorV1R\x05error2\xfb\x05\n" +
	"\x12PoolSessionService\x12f\n" +
	"\x11EnsureSessionPool\x12'.pool2of3.v1.EnsureSessionPoolRequestV1\x1a(.pool2of3.v1.EnsureSessionPoolResponseV1\x12]\n" +
	"\x0eGetSessionPool\x12$.pool2of3.v1.GetSessionPoolRequestV1\x1a%.pool2of3.v1.GetSessionPoolResponseV1\x12o\n" +
	"\x14PrepareTicketPayment\x12*.pool2of3.v1.PrepareTicketPaymentRequestV1\x1a+.pool2of3.v1.PrepareTicketPaymentResponseV1\x12l\n" +
	"\x13CommitTicketPayment\x12).pool2of3.v1.CommitTicketPaymentRequestV1\x1a*.pool2of3.v1.CommitTicketPaymentResponseV1\x12i\n" +
	"\x12AbortTicketPayment\x12(.pool2of3.v1.AbortTicketPaymentRequestV1\x1a).pool2of3.v1.AbortTicketPaymentResponseV1\x12c\n" +
	"\x10CloseSessionPool\x12&.pool2of3.v1.CloseSessionPoolRequestV1\x1a'.pool2of3.v1.CloseSessionPoolResponseV1\x12o\n" +
	"\x14ArbitrateSessionPool\x12*.pool2of3.v1.ArbitrateSessionPoolRequestV1\x1a+.pool2of3.v1.ArbitrateSessionPoolResponseV1B6Z4github.com/bsv8/go-bitfs/proto/pool2of3pb;pool2of3pbb\x06proto3"

var (
	file_proto_pool2of3_session_proto_rawDescOnce sync.Once
	file_proto_pool2of3_session_proto_rawDescData []byte
)

func file_proto_pool2of3_session_proto_rawDescGZIP() []byte {
	file_proto_pool2of3_session_proto_rawDescOnce.Do(func() {
		file_proto_pool2of3_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pool2of3_session_proto_rawDesc), len(file_proto_pool2of3_session_proto_rawDesc)))
	})
	return file_proto_pool2of3_session_proto_rawDescData
}

var file_proto_pool2of3_session_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_pool2of3_session_proto_goTypes = []any{
	(*PoolTicketRefV1)(nil),                // 0: pool2of3.v1.PoolTicketRefV1
	(*EnsureSessionPoolRequestV1)(nil),     // 1: pool2of3.v1.EnsureSessionPoolRequestV1
	(*EnsureSessionPoolResponseV1)(nil),    // 2: pool2of3.v1.EnsureSessionPoolResponseV1
	(*GetSessionPoolRequestV1)(nil),        // 3: pool2of3.v1.GetSessionPoolRequestV1
	(*GetSessionPoolResponseV1)(nil),       // 4: pool2of3.v1.GetSessionPoolResponseV1
	(*PrepareTicketPaymentRequestV1)(nil),  // 5: pool2of3.v1.PrepareTicketPaymentRequestV1
	(*PrepareTicketPaymentResponseV1)(nil), // 6: pool2of3.v1.PrepareTicketPaymentResponseV1
	(*CommitTicketPaymentRequestV1)(nil),   // 7: pool2of3.v1.CommitTicketPaymentRequestV1
	(*CommitTicketPaymentResponseV1)(nil),  // 8: pool2of3.v1.CommitTicketPaymentResponseV1
	(*AbortTicketPaymentRequestV1)(nil),    // 9: pool2of3.v1.AbortTicketPaymentRequestV1
	(*AbortTicketPaymentResponseV1)(nil),   // 10: pool2of3.v1.AbortTicketPaymentResponseV1
	(*CloseSessionPoolRequestV1)(nil),      // 11: pool2of3.v1.CloseSessionPoolRequestV1
	(*CloseSessionPoolResponseV1)(nil),     // 12: pool2of3.v1.CloseSessionPoolResponseV1
	(*PoolSessionRefV1)(nil),               // 13: pool2of3.v1.PoolSessionRefV1
	(*PoolErrorV1)(nil),                    // 14: pool2of3.v1.PoolErrorV1
	(PoolUpdateTxResultV1)(0),              // 15: pool2of3.v1.PoolUpdateTxResultV1
	(*ArbitrateSessionPoolRequestV1)(nil),  // 16: pool2of3.v1.ArbitrateSessionPoolRequestV1
	(*ArbitrateSessionPoolResponseV1)(nil), // 17: pool2of3.v1.ArbitrateSessionPoolResponseV1
}
var file_proto_pool2of3_session_proto_depIdxs = []int32{
	13, // 0: pool2of3.v1.EnsureSessionPoolResponseV1.session:type_name -> pool2of3.v1.PoolSessionRefV1
	14, // 1: pool2of3.v1.EnsureSessionPoolResponseV1.error:type_name -> pool2of3.v1.PoolErrorV1
	13, // 2: pool2of3.v1.GetSessionPoolResponseV1.session:type_name -> pool2of3.v1.PoolSessionRefV1
	14, // 3: pool2of3.v1.GetSessionPoolResponseV1.error:type_name -> pool2of3.v1.PoolErrorV1
	0,  // 4: pool2of3.v1.PrepareTicketPaymentRequestV1.ticket:type_name -> pool2of3.v1.PoolTicketRefV1
	14, // 5: pool2of3.v1.PrepareTicketPaymentResponseV1.error:type_name -> pool2of3.v1.PoolErrorV1
	0,  // 6: pool2of3.v1.CommitTicketPaymentRequestV1.ticket:type_name -> pool2of3.v1.PoolTicketRefV1
	15, // 7: pool2of3.v1.CommitTicketPaymentResponseV1.result:type_name -> pool2of3.v1.PoolUpdateTxResultV1
	14, // 8: pool2of3.v1.CommitTicketPaymentResponseV1.error:type_name -> pool2of3.v1.PoolErrorV1
	0,  // 9: pool2of3.v1.AbortTicketPaymentRequestV1.ticket:type_name -> pool2of3.v1.PoolTicketRefV1
	14, // 10: pool2of3.v1.AbortTicketPaymentResponseV1.error:type_name -> pool2of3.v1.PoolErrorV1
	14, // 11: pool2of3.v1.CloseSessionPoolResponseV1.error:type_name -> pool2of3.v1.PoolErrorV1
	1,  // 12: pool2of3.v1.PoolSessionService.EnsureSessionPool:input_type -> pool2of3.v1.EnsureSessionPoolRequestV1
	3,  // 13: pool2of3.v1.PoolSessionService.GetSessionPool:input_type -> pool2of3.v1.GetSessionPoolRequestV1
	5,  // 14: pool2of3.v1.PoolSessionService.PrepareTicketPayment:input_type -> pool2of3.v1.PrepareTicketPaymentRequestV1
	7,  // 15: pool2of3.v1.PoolSessionService.CommitTicketPayment:input_type -> pool2of3.v1.CommitTicketPaymentRequestV1
	9,  // 16: pool2of3.v1.PoolSessionService.AbortTicketPayment:input_type -> pool2of3.v1.AbortTicketPaymentRequestV1
	11, // 17: pool2of3.v1.PoolSessionService.CloseSessionPool:input_type -> pool2of3.v1.CloseSessionPoolRequestV1
	16, // 18: pool2of3.v1.PoolSessionService.ArbitrateSessionPool:input_type -> pool2of3.v1.ArbitrateSessionPoolRequestV1
	2,  // 19: pool2of3.v1.PoolSessionService.EnsureSessionPool:output_type -> pool2of3.v1.EnsureSessionPoolResponseV1
	4,  // 20: pool2of3.v1.PoolSessionService.GetSessionPool:output_type -> pool2of3.v1.GetSessionPoolResponseV1
	6,  // 21: pool2of3.v1.PoolSessionService.PrepareTicketPayment:output_type -> pool2of3.v1.PrepareTicketPaymentResponseV1
	8,  // 22: pool2of3.v1.PoolSessionService.CommitTicketPayment:output_type -> pool2of3.v1.CommitTicketPaymentResponseV1
	10, // 23: pool2of3.v1.PoolSessionService.AbortTicketPayment:output_type -> pool2of3.v1.AbortTicketPaymentResponseV1
	12, // 24: pool2of3.v1.PoolSessionService.CloseSessionPool:output_type -> pool2of3.v1.CloseSessionPoolResponseV1
	17, // 25: pool2of3.v1.PoolSessionService.ArbitrateSessionPool:output_type -> pool2of3.v1.ArbitrateSessionPoolResponseV1
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_pool2of3_session_proto_init() }
func file_proto_pool2of3_session_proto_init() {
	if File_proto_pool2of3_session_proto != nil {
		return
	}
	file_proto_pool2of3_arbiter_proto_init()
	file_proto_pool2of3_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pool2of3_session_proto_rawDesc), len(file_proto_pool2of3_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pool2of3_session_proto_goTypes,
		DependencyIndexes: file_proto_pool2of3_session_proto_depIdxs,
		MessageInfos:      file_proto_pool2of3_session_proto_msgTypes,
	}.Build()
	File_proto_pool2of3_session_proto = out.File
	file_proto_pool2of3_session_proto_goTypes = nil
	file_proto_pool2of3_session_proto_depIdxs = nil
}
