module.exports = {
  docsSidebar: [
    {type: 'doc', id: 'sdk/protocol-foundations-and-cbor', label: 'SDK foundations'},
    {
      type: 'category',
      label: 'SDK guides',
      items: [
        'sdk/external-hooks-and-data-types',
        'sdk/role-workflow-api',
        'sdk/implementation-roadmap',
        'sdk/sdk-api-framework-design',
      ],
    },
    {
      type: 'category',
      label: 'Protocol',
      items: [
        {type: 'autogenerated', dirName: 'protocol'},
      ],
    },
    {type: 'doc', id: 'migration/migrate-from-bsv8-gateway', label: 'Migration'},
    {
      type: 'category',
      label: 'Legacy',
      items: [{type: 'autogenerated', dirName: 'legacy'}],
    },
  ],
};
